/**
 * Catalog C–D: television, teletext, terminals and early graphical computing (1950–1994).
 */
import * as C from './compositions';
import { F, GF, pal, xp } from './presets';
import type { VisualExperience } from './types';

const TERM_AMBER = { '--glow': 'rgba(255,170,0,.45)', '--hi': '#ffd36b', '--dim': '#5a3e00', '--faint': '#2c1f00', '--dock-bg': '#050403', '--dock-border': '1px solid #6a4a00', '--modal-bg': '#080502', '--modal-border': '3px double #ffb000', '--titlebar-bg': '#ffb000', '--titlebar-ink': '#050403', '--chart-line': '#ffb000', '--chart-grid': '#3a2800', '--chart-bg': '#080502', '--chart-dash': '1 3', '--cell-pad': '0 6px', '--story-pad': '1px 0', '--story-rule': '0', '--empty-style': 'normal' };

export const MID_CATALOG: VisualExperience[] = [
  // ======================================================================= C. 1950–1979
  xp({
    id: 'midcentury-1950', name: 'Mid-Century Newspaper', from: '1950-01-01', to: '1954-12-31', family: 'print', archetype: 'midcentury',
    rationale: 'Early-1950s metropolitan press: strong sans-serif section mastheads, a four-column newspaper grid, black-and-white photography (here, the day’s real front-page scans).',
    publication: 'Market Times', motto: 'Financial Edition', price: '5¢',
    typography: { head: F.jost, body: F.bask, num: F.courier, lead: F.jost, fs: '14.5px', lh: '1.5', leadFs: '40px', leadFw: '700', storyFs: '16px', storyFw: '600', sectionFs: '13px', sectionTt: 'uppercase', sectionLs: '.14em', sectionFw: '700', fonts: [...GF.deco, ...GF.bask, ...GF.courier] },
    palette: pal({ bg: '#ebe2cf', paper: '#f6f0e2', panel: '#e6d8bb', ink: '#2a2622', ink2: '#3a342d', mute: '#776c5d', rule: '#b7a88d', accent: '#c4562b', onAccent: '#fff7ea', up: '#2f6b4f', down: '#b0402a', link: '#2a2622' }),
    spacing: { maxw: '1200px', radius: '2px' }, tokens: { '--row-rule': '1px dashed rgba(0,0,0,.14)', '--olive': '#6b6f3a', '--teal': '#2f6b6b', '--accent-ink': '#a8431d' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger',
    interactions: ['section-jump', 'expand-articles'], decor: ['ink-grain'], chart: 'print', ticker: 'bulletin',
    motion: { profile: 'still', enter: 'warmup .9s ease-out both' }, loading: 'Setting type…',
    details: ['Photograph slots filled by real front-page scans', 'Bulletin strip under the masthead'], opts: { native: true },
  }),
  xp({
    id: 'tv-1955', name: 'Early Television News', from: '1955-01-01', to: '1959-12-31', family: 'broadcast', archetype: 'broadcast',
    rationale: 'Black-and-white network news: a cabinet television set, hand-lettered title cards, and simple bulletin graphics over a monochrome CRT.',
    publication: 'Market Times', motto: 'Evening Newscast', price: '10¢',
    typography: { head: F.jost, body: F.bask, num: F.courier, lead: F.jost, fs: '14.5px', lh: '1.5', leadFs: '38px', leadFw: '700', storyFs: '15.5px', storyFw: '600', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.16em', sectionFw: '700', fonts: [...GF.deco, ...GF.bask, ...GF.courier] },
    palette: pal({ bg: '#1b1b1a', paper: '#e4e2da', ink: '#171715', ink2: '#2c2b28', mute: '#6a675f', rule: '#8f8c82', accent: '#2a2a28', onAccent: '#f1efe6', up: '#1f1f1d', down: '#1f1f1d', link: '#171715', panel: '#2b2b29' }),
    background: 'radial-gradient(ellipse at 50% 0%, #34342f, #131312 70%)',
    spacing: { maxw: '1180px', radius: '3px' }, tokens: { '--accent-2': '#d9d6cb', '--dock-bg': '#2b2b29', '--dock-ink': '#e4e2da', '--dock-border': '0', '--modal-bg': '#e4e2da', '--titlebar-bg': '#2a2a28', '--titlebar-ink': '#f1efe6', '--co-rule': '4px solid #2a2a28', '--chart-line': '#2a2a28', '--tv-cabinet': 'linear-gradient(160deg,#6a5238,#3a2a1a 60%,#55412a)', '--tv-screen': 'radial-gradient(120% 120% at 50% 40%, #50534f 0%, #292b29 60%, #0e0f0e 100%)', '--tv-grayscale': '1' },
    nav: { model: 'dial' }, search: 'inquiry', market: 'board', news: 'bulletins', portfolio: 'ledger',
    interactions: ['tune-dial', 'expand-articles'], decor: ['tv-bezel', 'scanlines', 'vignette'], chart: 'print', ticker: 'crawl',
    motion: { profile: 'subtle', enter: 'tv-on .7s ease-out both' }, loading: 'Please stand by…',
    details: ['Monochrome picture tube with scan lines', 'Hand-lettered “Evening Newscast” title card'], opts: { skin: 'fifties' },
  }),
  xp({
    id: 'swiss-1960', name: 'Modernist Financial Editorial', from: '1960-01-01', to: '1964-12-31', family: 'print', archetype: 'swiss',
    rationale: 'International Typographic Style applied to business publishing: a twelve-column grid, flush-left sans-serif type, one red accent, generous white space.',
    publication: 'Market Times', motto: 'Business · Finance · Economy', price: '15¢',
    typography: { head: F.swiss, body: F.swiss, num: F.swiss, lead: F.swiss, fs: '14.5px', lh: '1.5', leadFs: '46px', leadFw: '700', storyFs: '16px', storyFw: '600', sectionFs: '11px', sectionTt: 'uppercase', sectionLs: '.12em', sectionFw: '700', fonts: GF.inter },
    palette: pal({ bg: '#f2f0ec', paper: '#ffffff', ink: '#111111', ink2: '#2b2b2b', mute: '#6e6e6e', rule: '#111111', accent: '#d8001b', onAccent: '#ffffff', up: '#111111', down: '#d8001b', link: '#111111' }),
    spacing: { maxw: '1240px', radius: '0px' }, tokens: { '--row-rule': '1px solid rgba(0,0,0,.12)', '--lead-ls': '-.03em', '--dock-bg': '#111', '--dock-ink': '#fff', '--dock-border': '0', '--co-rule': '3px solid #111' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.SWISS,
    interactions: ['section-jump', 'expand-articles'], decor: [], chart: 'print', ticker: 'none',
    motion: { profile: 'still', enter: 'none' }, loading: 'Setting type…',
    details: ['Twelve-column asymmetric grid', 'A single red accent rule'], opts: {},
  }),
  xp({
    id: 'space-1965', name: 'Space-Age Broadcast', from: '1965-01-01', to: '1969-12-31', family: 'broadcast', archetype: 'broadcast',
    rationale: 'Mid-1960s network news: modernist geometry, a console television, broadcast news strips, space-age type and the evening newscast structure.',
    publication: 'Market Times', motto: 'and the Evening Report', price: '10¢',
    typography: { head: F.jost, body: F.bask, num: F.courier, lead: F.jost, fs: '14.5px', lh: '1.5', leadFs: '40px', leadFw: '700', storyFs: '15.5px', storyFw: '600', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.16em', sectionFw: '700', fonts: [...GF.deco, ...GF.bask, ...GF.courier] },
    palette: pal({ bg: '#e3edf0', paper: '#f6fafb', ink: '#10222b', ink2: '#25404c', mute: '#51676f', rule: '#a9bcc4', accent: '#0f6f82', onAccent: '#ffffff', up: '#1d7a52', down: '#b8381f', link: '#10222b' }),
    spacing: { maxw: '1220px', radius: '10px' }, tokens: { '--accent-2': '#d9501f', '--dock-bg': '#10222b', '--dock-ink': '#f6fafb', '--dock-border': '0', '--titlebar-bg': '#0f6f82', '--titlebar-ink': '#ffffff', '--co-rule': '4px solid #0f6f82', '--tv-cabinet': 'linear-gradient(155deg,#fbfcfc,#c9d2d6 42%,#eef2f3 58%,#a5b1b8)', '--tv-screen': 'radial-gradient(120% 120% at 50% 40%,#2a6572 0%,#143a45 60%,#07181d 100%)' },
    nav: { model: 'dial' }, search: 'inquiry', market: 'board', news: 'bulletins', portfolio: 'ledger',
    interactions: ['tune-dial', 'expand-articles'], decor: ['tv-bezel', 'scanlines'], chart: 'print', ticker: 'crawl',
    motion: { profile: 'subtle', enter: 'tv-on .7s ease-out both' }, loading: 'Please stand by…',
    details: ['Channel dial navigation', 'Sports scores crawl along the bottom of the screen'], opts: { native: true, skin: 'sixties' },
    labels: {},
  }),
  xp({
    id: 'colortv-1970', name: 'Colour Television News', from: '1970-01-01', to: '1973-12-31', family: 'broadcast', archetype: 'broadcast',
    rationale: 'Early-1970s colour newscasts: saturated broadcast browns and oranges, rounded slab type, bold lower-third banners, large information panels.',
    publication: 'Market Times', motto: 'Eyewitness Business Report', price: '20¢',
    typography: { head: F.bree, body: F.bask, num: F.courier, lead: F.slab, fs: '14.5px', lh: '1.5', leadFs: '38px', leadFw: '400', storyFs: '15.5px', storyFw: '600', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.12em', sectionFw: '700', fonts: [...GF.bree, ...GF.slab, ...GF.bask, ...GF.courier] },
    palette: pal({ bg: '#efe1c4', paper: '#f8eeda', ink: '#2b1d12', ink2: '#3d2b1c', mute: '#7a6450', rule: '#c7a982', accent: '#b5531c', onAccent: '#ffffff', up: '#2f6b4f', down: '#b0402a', link: '#2b1d12' }),
    spacing: { maxw: '1220px', radius: '10px' }, tokens: { '--accent-2': '#6b4a2b', '--dock-bg': '#2b1d12', '--dock-ink': '#f8eeda', '--dock-border': '0', '--titlebar-bg': '#b5531c', '--titlebar-ink': '#fff', '--co-rule': '4px solid #b5531c', '--tv-cabinet': 'linear-gradient(160deg,#8a5a33,#5a3a20 55%,#7a4f2c)', '--tv-screen': 'radial-gradient(120% 120% at 40% 30%,#ffe9c9 0%,#e0a873 45%,#8c5a3a 100%)' },
    nav: { model: 'dial' }, search: 'inquiry', market: 'board', news: 'bulletins', portfolio: 'ledger', composition: C.COLOR_TV,
    interactions: ['tune-dial', 'expand-articles'], decor: ['tv-bezel', 'scanlines'], chart: 'print', ticker: 'crawl',
    motion: { profile: 'subtle', enter: 'tv-on .7s ease-out both' }, loading: 'Please stand by…',
    details: ['Full-width lower-third banner on the lead story', 'Warm colour-set palette'], opts: { skin: 'seventies', lowerThird: true },
  }),
  xp({
    id: 'teletext-1974', name: 'Early Teletext', from: '1974-01-01', to: '1976-12-31', family: 'broadcast', archetype: 'teletext',
    rationale: 'Broadcast teletext (Ceefax/Oracle era): a 40×24 block-character grid, seven colours, three-digit page numbers and four coloured navigation keys.',
    publication: 'MARKET TEXT', motto: 'Page 100', price: undefined, module: 'terminal',
    typography: { head: F.teletext, body: F.teletext, num: F.teletext, lead: F.teletext, fs: '21px', lh: '1.1', leadFs: '30px', leadFw: '400', storyFs: '21px', storyFw: '400', sectionFs: '21px', sectionTt: 'uppercase', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#000000', paper: '#000000', ink: '#ffffff', ink2: '#e6e6e6', mute: '#00ffff', rule: '#00ffff', accent: '#ffff00', onAccent: '#000000', up: '#00ff00', down: '#ff3030', link: '#00ffff', focus: '#ffff00' }),
    spacing: { maxw: '980px', gutter: '10px', mainPad: '8px', cellPad: '0 6px', radius: '0' },
    tokens: { '--story-pad': '0', '--story-rule': '0', '--row-rule': '0', '--empty-style': 'normal', '--chart-line': '#00ffff', '--chart-grid': '#0a3a3a', '--chart-bg': '#000', '--chart-dash': '2 2', '--dock-bg': '#000', '--dock-border': '2px solid #00ffff', '--modal-bg': '#000', '--modal-border': '2px solid #ffff00', '--titlebar-bg': '#0000ff', '--titlebar-ink': '#fff', '--glow': 'transparent', '--hi': '#ffff00', '--dim': '#00aaaa', '--faint': '#003c3c' },
    nav: { model: 'pagenum' }, search: 'pagenum', market: 'table', news: 'strips', portfolio: 'terminal', composition: C.TELETEXT,
    interactions: ['teletext-pages', 'expand-articles'], decor: ['scanlines'], chart: 'pixel', ticker: 'none',
    motion: { profile: 'subtle', enter: 'tt-on .5s steps(6) both' }, loading: 'WAITING FOR PAGE…',
    details: ['Type a three-digit page number (100 index, 120 markets, 200 portfolio)', 'Red / green / yellow / cyan navigation keys', 'Mosaic block header'], opts: { service: 'MARKET TEXT', style: 'ceefax' },
  }),
  xp({
    id: 'videotex-1977', name: 'Videotex Financial Information Service', from: '1977-01-01', to: '1979-12-31', family: 'broadcast', archetype: 'teletext',
    rationale: 'Viewdata / videotex services (Prestel-style): a blue frame, character-cell graphics, numeric menu navigation and data-table pages for financial subscribers.',
    publication: 'MARKET VIEW', motto: 'Financial Information Service', price: undefined, module: 'terminal',
    typography: { head: F.teletext, body: F.teletext, num: F.teletext, lead: F.teletext, fs: '21px', lh: '1.1', leadFs: '28px', leadFw: '400', storyFs: '21px', storyFw: '400', sectionFs: '21px', sectionTt: 'uppercase', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#00006e', paper: '#00006e', ink: '#ffffff', ink2: '#e6e6ff', mute: '#9ad7ff', rule: '#ffff00', accent: '#ffff00', onAccent: '#00006e', up: '#44ff88', down: '#ff7a7a', link: '#ffff00', focus: '#ffffff' }),
    spacing: { maxw: '980px', gutter: '10px', mainPad: '8px', cellPad: '0 6px', radius: '0' },
    tokens: { '--story-pad': '0', '--story-rule': '0', '--row-rule': '0', '--empty-style': 'normal', '--chart-line': '#ffff00', '--chart-grid': '#1a1a96', '--chart-bg': '#00006e', '--chart-dash': '2 2', '--dock-bg': '#00004a', '--dock-border': '2px solid #ffff00', '--modal-bg': '#00006e', '--modal-border': '2px solid #ffff00', '--titlebar-bg': '#ffff00', '--titlebar-ink': '#00006e', '--glow': 'transparent', '--hi': '#ffff00', '--dim': '#9ad7ff', '--faint': '#0a0a90' },
    nav: { model: 'pagenum' }, search: 'pagenum', market: 'table', news: 'strips', portfolio: 'terminal', composition: C.TELETEXT,
    interactions: ['teletext-pages', 'expand-articles'], decor: ['scanlines'], chart: 'pixel', ticker: 'none',
    motion: { profile: 'subtle', enter: 'tt-on .5s steps(6) both' }, loading: 'CONNECTING…',
    details: ['Numeric page keys with a "*#" style prompt', 'Yellow-on-blue price tables'], opts: { service: 'MARKET VIEW', style: 'prestel' },
  }),

  // ======================================================================= D. 1980–1994
  xp({
    id: 'green-1980', name: 'Green Phosphor Terminal', from: '1980-01-01', to: '1982-12-31', family: 'terminal', archetype: 'terminal',
    rationale: 'Early timesharing and videotext terminals: monochrome green phosphor, box-drawing frames, keyboard-only operation and dense quotation tables.',
    publication: 'MTM TIMESHARING SERVICE', motto: 'REL 2.1', module: 'terminal',
    typography: { head: F.vt, body: F.vt, num: F.vt, lead: F.vt, fs: '19px', lh: '1.15', leadFs: '30px', leadFw: '400', storyFs: '19px', storyFw: '400', sectionFs: '19px', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#010a03', paper: '#02110a', ink: '#37ff7a', ink2: '#2be66a', mute: '#1f9c4a', rule: '#15702f', accent: '#37ff7a', onAccent: '#010a03', up: '#c9ffd9', down: '#1fb351', link: '#9dffbf', focus: '#c9ffd9' }),
    spacing: { maxw: '1320px', gutter: '14px', mainPad: '10px' },
    tokens: { ...TERM_AMBER, '--glow': 'rgba(55,255,122,.5)', '--hi': '#c9ffd9', '--dim': '#10602a', '--faint': '#062812', '--dock-bg': '#010a03', '--dock-border': '1px solid #15702f', '--modal-bg': '#02110a', '--modal-border': '3px double #37ff7a', '--titlebar-bg': '#37ff7a', '--titlebar-ink': '#010a03', '--chart-line': '#37ff7a', '--chart-grid': '#0a3a1a', '--chart-bg': '#02110a' },
    nav: { model: 'fkeys' }, search: 'command', market: 'table', news: 'strips', portfolio: 'terminal', composition: C.GREEN_SCREENS,
    interactions: ['fkeys', 'command-line', 'screens'], decor: ['scanlines', 'vignette'], chart: 'phosphor', ticker: 'terminal',
    motion: { profile: 'subtle', enter: 'crt-on .7s cubic-bezier(.2,.9,.2,1) both' }, loading: 'RETRIEVING DATA…',
    details: ['Numbered screens 1–4 (also number keys)', 'Green phosphor glow, bloom and screen curvature', 'Headlines type themselves out row by row; a block cursor blinks on the command line', 'Errors ring the bell with a screen flash'], opts: { phosphor: 'green', screens: 'numbers' },
  }),
  xp({
    id: 'amber-1983', name: 'Amber Financial Terminal', from: '1983-01-01', to: '1984-12-31', family: 'terminal', archetype: 'terminal',
    rationale: 'Dedicated financial-information terminals: amber on black, structured quote screens selected with function keys, a status line with the clock.',
    publication: 'MTM FINANCIAL INFORMATION SYSTEM', motto: 'REL 3.0', module: 'terminal',
    typography: { head: F.vt, body: F.vt, num: F.vt, lead: F.vt, fs: '19px', lh: '1.15', leadFs: '32px', leadFw: '400', storyFs: '19px', storyFw: '400', sectionFs: '19px', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#050403', paper: '#0b0805', ink: '#ffb000', ink2: '#e8a200', mute: '#a97600', rule: '#6a4a00', accent: '#ffb000', onAccent: '#050403', up: '#ffe08a', down: '#c27a00', link: '#ffd36b', focus: '#ffd36b' }),
    spacing: { maxw: '1320px', gutter: '14px', mainPad: '10px' }, tokens: TERM_AMBER,
    nav: { model: 'fkeys' }, search: 'command', market: 'table', news: 'strips', portfolio: 'terminal', composition: C.AMBER_SCREENS,
    interactions: ['fkeys', 'command-line', 'screens'], decor: ['scanlines', 'vignette'], chart: 'phosphor', ticker: 'terminal',
    motion: { profile: 'subtle', enter: 'crt-on .7s cubic-bezier(.2,.9,.2,1) both' }, loading: 'RETRIEVING DATA…',
    details: ['F1–F4 select NEWS / QUOTES / CHART / ECON screens', 'Field-labelled status line (SCREEN, FUNC, MKT, PAGE) and a function-key legend', 'Reverse-video selection under the pointer or keyboard focus'], opts: { phosphor: 'amber', screens: 'fkeys' },
  }),
  xp({
    id: 'dos-1985', name: 'DOS Information Service', from: '1985-01-01', to: '1986-12-31', family: 'terminal', archetype: 'dos',
    rationale: 'Dial-up information services on the IBM PC: cyan and white text on blue, ASCII-framed menus and numeric shortcuts.',
    publication: 'MTM-NET', motto: 'Information Service for the Personal Computer', module: 'terminal',
    typography: { head: F.plexmono, body: F.plexmono, num: F.plexmono, lead: F.plexmono, fs: '16px', lh: '1.3', leadFs: '24px', leadFw: '600', storyFs: '16px', storyFw: '400', sectionFs: '16px', sectionFw: '600', sectionTt: 'uppercase', fonts: GF.vt },
    palette: pal({ bg: '#0000aa', paper: '#0000aa', ink: '#e8e8e8', ink2: '#ffffff', mute: '#55ffff', rule: '#55ffff', accent: '#ffff55', onAccent: '#0000aa', up: '#55ff55', down: '#ff5555', link: '#55ffff', focus: '#ffff55' }),
    spacing: { maxw: '1100px', gutter: '14px', mainPad: '10px', cellPad: '0 8px' },
    tokens: { '--story-pad': '2px 0', '--story-rule': '0', '--row-rule': '0', '--empty-style': 'normal', '--glow': 'transparent', '--hi': '#ffff55', '--dim': '#55ffff', '--faint': '#0000ee', '--dock-bg': '#0000aa', '--dock-border': '2px solid #55ffff', '--modal-bg': '#0000aa', '--modal-border': '3px double #55ffff', '--titlebar-bg': '#aaaaaa', '--titlebar-ink': '#000000', '--chart-line': '#ffff55', '--chart-grid': '#2020cc', '--chart-bg': '#0000aa', '--chart-dash': '2 2' },
    nav: { model: 'menu' }, search: 'command', market: 'table', news: 'list', portfolio: 'terminal', composition: C.DOS_MENU,
    interactions: ['numeric-menu', 'command-line', 'screens'], decor: [], chart: 'pixel', ticker: 'none',
    motion: { profile: 'still', enter: 'none' }, loading: 'PLEASE WAIT…',
    details: ['Press 1–4 to open a menu option, 0 for the menu, Esc to return, P portfolio, F find', 'Menu bar with highlighted hot-keys, double-line boxes with drop shadows, function-key bar', 'A "Press ENTER" prompt returns from sub-screens'], opts: { menuStyle: 'dos' },
  }),
  xp({
    id: 'workstation-1987', name: 'Crash-Era Financial Workstation', from: '1987-01-01', to: '1988-12-31', family: 'terminal', archetype: 'workstation',
    rationale: 'Late-1980s trading-desk workstations: several panes at once — wires, quote boards, indices — with price changes highlighted and a command line along the bottom.',
    publication: 'MTM FINANCIAL INFORMATION SYSTEM', motto: 'REL 4.2', module: 'terminal',
    typography: { head: F.vt, body: F.vt, num: F.vt, lead: F.vt, fs: '19px', lh: '1.15', leadFs: '32px', leadFw: '400', storyFs: '19px', storyFw: '400', sectionFs: '19px', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#050403', paper: '#0b0805', ink: '#ffb000', ink2: '#e8a200', mute: '#a97600', rule: '#6a4a00', accent: '#ffb000', onAccent: '#050403', up: '#59ff8f', down: '#ff5c4d', link: '#ffd36b', focus: '#ffd36b' }),
    spacing: { maxw: '1320px', gutter: '14px', mainPad: '10px' }, tokens: TERM_AMBER,
    nav: { model: 'fkeys' }, composition: C.AMBER_SCREENS, search: 'command', market: 'board', news: 'strips', portfolio: 'terminal',
    interactions: ['fkeys', 'command-line', 'screens'], decor: ['scanlines', 'vignette'], chart: 'phosphor', ticker: 'terminal',
    motion: { profile: 'subtle', enter: 'crt-on .7s cubic-bezier(.2,.9,.2,1) both' }, loading: 'RETRIEVING DATA…',
    details: ['Six simultaneous panes with a command line', 'Command history (↑/↓) and F-key shortcuts', 'Quote changes flash on update', 'Scrolling news tape, status bar, Tab completes commands and tickers, BUY prints an order ticket', 'Optional CRT effect (toggle with the CRT key)'], opts: { native: true, phosphor: 'amber', crtToggle: true },
  }),
  xp({
    id: 'mono-1989', name: 'Early Graphical Desktop', from: '1989-01-01', to: '1990-12-31', family: 'desktop', archetype: 'desktop',
    rationale: 'First-generation graphical desktops: 1-bit black-and-white windows with pixel borders, a menu bar with pull-downs, folder icons and draggable windows.',
    publication: 'MarketDesk', motto: 'System 1.0', module: 'web',
    typography: { head: F.vt, body: F.vt, num: F.vt, lead: F.vt, fs: '19px', lh: '1.15', leadFs: '26px', leadFw: '400', storyFs: '19px', storyFw: '400', sectionFs: '19px', sectionFw: '400', fonts: GF.vt },
    palette: pal({ bg: '#a8a8a8', paper: '#ffffff', ink: '#000000', ink2: '#000000', mute: '#555555', rule: '#000000', accent: '#000000', onAccent: '#ffffff', up: '#000000', down: '#000000', link: '#000000', focus: '#000000' }),
    background: 'repeating-conic-gradient(#000 0% 25%, #fff 0% 50%) 0 0 / 4px 4px',
    spacing: { maxw: '1400px', gutter: '0', mainPad: '0', radius: '0' },
    tokens: { '--dock-bg': '#fff', '--dock-border': '2px solid #000', '--modal-bg': '#fff', '--modal-border': '2px solid #000', '--modal-shadow': '3px 3px 0 #000', '--titlebar-bg': 'repeating-linear-gradient(#000 0 1px, #fff 1px 3px)', '--titlebar-ink': '#000', '--chart-line': '#000', '--chart-grid': '#888', '--chart-dash': '1 2', '--chart-bg': '#fff', '--cell-pad': '0 6px', '--story-rule': '0', '--empty-style': 'normal', '--desk': '#a8a8a8' },
    nav: { model: 'icons' }, search: 'form', market: 'table', news: 'list', portfolio: 'cards', composition: C.DESKTOP_WINDOWS,
    interactions: ['movable-windows', 'dropdown-nav', 'hyperlinks'], decor: ['bevel'], chart: 'pixel', ticker: 'none',
    motion: { profile: 'still', enter: 'none' }, loading: 'Please wait…',
    details: ['Striped title bars with close and zoom boxes; drag by the title, resize from the corner grip', 'Double-click an icon to open it; arrow keys, Enter and Escape work everywhere', 'Pull-down menus with keyboard arrows, About and Control Panel dialogs, a choice of dithered desk patterns', 'A short Welcome splash at startup'], opts: { skin: 'mono' }, status: 'complete',
  }),
  xp({
    id: 'win3-1991', name: 'Windows 3.x-Style Environment', from: '1991-01-01', to: '1992-12-31', family: 'desktop', archetype: 'desktop',
    rationale: 'Early-1990s PC graphical shells: a Program-Manager-style group window, grey beveled controls, navy title bars and a teal desktop.',
    publication: 'MarketMan', motto: 'Program Manager', module: 'web',
    typography: { head: F.arial, body: F.arial, num: F.arial, lead: F.arial, fs: '13px', lh: '1.3', leadFs: '22px', leadFw: '700', storyFs: '13px', storyFw: '400', sectionFs: '13px', sectionFw: '700' },
    palette: pal({ bg: '#008080', paper: '#ffffff', panel: '#c0c0c0', ink: '#000000', ink2: '#000000', mute: '#555555', rule: '#808080', accent: '#000080', onAccent: '#ffffff', up: '#006400', down: '#cc0000', link: '#000080', focus: '#000080' }),
    spacing: { maxw: '1400px', gutter: '0', mainPad: '0', radius: '0' },
    tokens: { '--dock-bg': '#c0c0c0', '--dock-border': '2px outset #fff', '--modal-bg': '#c0c0c0', '--modal-border': '2px outset #fff', '--modal-shadow': '2px 2px 0 #000', '--titlebar-bg': '#000080', '--titlebar-ink': '#fff', '--chart-line': '#000080', '--chart-grid': '#c0c0c0', '--chart-dash': 'none', '--chart-bg': '#fff', '--chart-border': '2px inset #c0c0c0', '--cell-pad': '1px 4px', '--story-rule': '0', '--desk': '#008080' },
    nav: { model: 'icons' }, search: 'form', market: 'table', news: 'list', portfolio: 'cards', composition: C.DESKTOP_WINDOWS,
    interactions: ['movable-windows', 'dropdown-nav', 'hyperlinks'], decor: ['bevel'], chart: 'pixel', ticker: 'none',
    motion: { profile: 'still', enter: 'none' }, loading: 'Please wait…',
    details: ['Program Manager group window with a grid of program icons (double-click to open)', 'Control-menu box, minimise and maximise arrows, active navy and inactive white title bars, size grip', 'Minimised windows sit as icons along the bottom of the desktop', 'Menu bar with underlined mnemonics (Alt+letter, F10), Cascade / Tile, About and Control Panel dialogs'], opts: { skin: 'win3' }, status: 'complete',
  }),
  xp({
    id: 'hypertext-1993', name: 'Early Hypertext Documents', from: '1993-01-01', to: '1994-12-31', family: 'earlyweb', archetype: 'hypertext',
    rationale: 'The first graphical browsers (Mosaic era): a plain grey page, black Times text, underlined blue links, headings and horizontal rules. No tables, no images, almost no layout.',
    publication: 'The Market Time Document', motto: 'A hypertext guide', module: 'web',
    typography: { head: F.times, body: F.times, num: "'Courier New', Courier, monospace", lead: F.times, fs: '17px', lh: '1.25', leadFs: '28px', leadFw: '700', storyFs: '17px', storyFw: '400', sectionFs: '22px', sectionFw: '700' },
    palette: pal({ bg: '#c0c0c0', paper: '#c0c0c0', ink: '#000000', ink2: '#000000', mute: '#444444', rule: '#808080', accent: '#0000ee', onAccent: '#ffffff', up: '#006400', down: '#a00000', link: '#0000ee', focus: '#0000ee' }),
    spacing: { maxw: '720px', gutter: '16px', mainPad: '10px', radius: '0' },
    tokens: { '--link-deco': 'underline', '--section-ink': '#000', '--chart-line': '#0000ee', '--chart-grid': '#a0a0a0', '--chart-dash': 'none', '--chart-bg': '#c0c0c0', '--dock-bg': '#c0c0c0', '--dock-border': '2px outset #fff', '--modal-bg': '#c0c0c0', '--modal-border': '2px outset #fff', '--titlebar-bg': '#000080', '--titlebar-ink': '#fff', '--story-rule': '0', '--empty-style': 'normal' },
    nav: { model: 'links' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.HYPERTEXT,
    interactions: ['hyperlinks'], decor: [], chart: 'pixel', ticker: 'none', headlineCase: 'title',
    motion: { profile: 'still', enter: 'none' }, loading: 'Transferring document…',
    details: ['Document title bar with Back / Forward / Home', 'Underlined links turn purple once visited', '“Document: Done.” status line'], opts: { chrome: 'mosaic' },
    status: 'complete',
  }),
];
