/**
 * Catalog A–C: print, early broadcast and modern print (before 1980).
 * Dates are design targets, not claims that every publication of the time looked alike.
 */
import * as C from './compositions';
import { F, GF, pal, xp } from './presets';
import type { VisualExperience } from './types';


export const PRINT_CATALOG: VisualExperience[] = [
  // ======================================================================= A. pre-1900
  xp({
    id: 'newsbook-1600', name: 'Early Printed Newsbook', from: '1000-01-01', to: '1699-12-31', family: 'print', archetype: 'gazette',
    rationale: 'English "corantos" and newsbooks: one dense column, black-letter masthead, woodcut ornaments, a merchant-price list printed on the back leaf.',
    publication: 'The Weekly Mercury', motto: 'Printed for the Satisfaction of Merchants and Others', price: 'ONE PENNY',
    typography: { head: F.fellSC, body: F.fell, num: F.fell, lead: F.fellDP, fs: '17px', lh: '1.5', leadFs: '27px', leadFw: '400', storyFs: '16px', storyFw: '400', sectionFs: '14px', sectionTt: 'uppercase', sectionLs: '.14em', sectionFw: '400', fonts: [...GF.fell, ...GF.black] },
    palette: pal({ bg: '#dccba2', paper: '#e8d9b5', ink: '#1b1409', ink2: '#2b2012', mute: '#6a5a3a', rule: '#3a2d16', accent: '#7a1f12', onAccent: '#f1e4c2', up: '#1b1409', down: '#1b1409', link: '#1b1409' }),
    background: 'radial-gradient(ellipse at 50% 0%, rgba(255,243,205,.5), transparent 60%), repeating-radial-gradient(circle at 23% 41%, rgba(70,50,20,.035) 0 1px, transparent 1px 3px), #dccba2',
    spacing: { maxw: '860px' }, tokens: { '--section-gap': '22px', '--row-rule': '1px dotted rgba(58,45,22,.45)', '--story-rule': '0', '--dock-bg': '#e8d9b5', '--dock-border': '3px double #3a2d16', '--modal-bg': '#e8d9b5', '--modal-border': '3px double #3a2d16' },
    nav: { model: 'pages' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.NEWSBOOK,
    interactions: ['turn-pages', 'expand-articles'], decor: ['woodcut', 'fleuron', 'ink-grain', 'ornament-rule'], ticker: 'none', chart: 'engraved',
    motion: { profile: 'still', enter: 'develop 1.1s ease-out both' }, loading: 'Setting type…',
    details: ['Decorative initial letter on the lead story', 'Page-turn navigation between leaves', 'Woodcut-style masthead ornament'],
    opts: { pageNoun: 'Leaf', masthead: 'black', arms: 'woodcut' },
  }),
  xp({
    id: 'gazette-1700', name: 'Colonial Gazette', from: '1700-01-01', to: '1749-12-31', family: 'print', archetype: 'gazette',
    rationale: 'Colonial-American and Georgian gazettes: four narrow columns, formal masthead with a royal-arms style cut, Foreign Advices, a Marine List of shipping and commodity prices.',
    publication: 'The Colonial Gazette', motto: 'Containing the Freshest Advices, Foreign and Domestick', price: 'THREE PENCE',
    typography: { head: F.fellSC, body: F.fell, num: F.fell, lead: F.fellDW, fs: '14.5px', lh: '1.4', leadFs: '22px', leadFw: '400', storyFs: '14px', storyFw: '400', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.12em', sectionFw: '400', fonts: GF.fell },
    palette: pal({ bg: '#d9c9a0', paper: '#e9ddc0', ink: '#16110a', ink2: '#2a2112', mute: '#66563a', rule: '#2f2512', accent: '#1b2a4a', onAccent: '#eee3c6', up: '#16110a', down: '#16110a', link: '#16110a' }),
    background: 'repeating-linear-gradient(0deg, rgba(60,45,20,.03) 0 1px, transparent 1px 4px), #d9c9a0',
    spacing: { maxw: '1100px' }, tokens: { '--section-gap': '16px', '--row-rule': '1px dotted rgba(47,37,18,.4)', '--story-rule': '0', '--dock-bg': '#e9ddc0', '--dock-border': '3px double #2f2512', '--modal-bg': '#e9ddc0', '--modal-border': '3px double #2f2512' },
    nav: { model: 'pages' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.COLONIAL,
    interactions: ['turn-pages', 'expand-articles'], decor: ['engraved-border', 'fleuron', 'ink-grain'], chart: 'engraved',
    motion: { profile: 'still', enter: 'develop 1s ease-out both' }, loading: 'Setting type…',
    details: ['Engraved-style border around the masthead', 'Marine List and Prices Current on the second leaf'],
    opts: { pageNoun: 'Page', masthead: 'fell', arms: 'engraved' },
  }),
  xp({
    id: 'gazette-1750', name: 'Enlightenment Newspaper', from: '1750-01-01', to: '1799-12-31', family: 'print', archetype: 'gazette',
    rationale: 'Late 18th-century papers: three structured columns, a stronger typographic hierarchy, printed Notices set in ruled boxes, engraved-style separators.',
    publication: 'The Public Intelligencer', motto: 'Open to All Parties, but Influenced by None', price: 'TWO PENCE',
    typography: { head: F.oldstd, body: F.oldstd, num: F.oldstd, lead: F.oldstd, fs: '15px', lh: '1.42', leadFs: '26px', leadFw: '700', storyFs: '14.5px', storyFw: '700', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.16em', sectionFw: '700', fonts: [...GF.oldstd, ...GF.fell] },
    palette: pal({ bg: '#e5dac0', paper: '#efe6cf', ink: '#17130b', ink2: '#2a2314', mute: '#6a5d42', rule: '#352b16', accent: '#5a1a1a', onAccent: '#f2e9d1', up: '#17130b', down: '#17130b', link: '#17130b' }),
    background: 'radial-gradient(ellipse at 20% 10%, rgba(255,248,225,.5), transparent 55%), #e5dac0',
    spacing: { maxw: '1120px' }, tokens: { '--section-gap': '18px', '--row-rule': '1px dotted rgba(53,43,22,.4)', '--story-rule': '0', '--dock-bg': '#efe6cf', '--dock-border': '3px double #352b16', '--modal-bg': '#efe6cf', '--modal-border': '3px double #352b16' },
    nav: { model: 'pages' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.ENLIGHTENMENT,
    interactions: ['turn-pages', 'expand-articles'], decor: ['ornament-rule', 'fleuron', 'ink-grain'], chart: 'engraved',
    motion: { profile: 'still', enter: 'develop 1s ease-out both' }, loading: 'Setting type…',
    details: ['Printer’s Notice set in a ruled box', 'Roman-numeral volume numbers', 'Fleuron separators between articles'],
    opts: { pageNoun: 'Page', masthead: 'oldstd', arms: 'rule' },
  }),
  xp({
    id: 'mercantile-1800', name: 'Mercantile Broadsheet', from: '1800-01-01', to: '1829-12-31', family: 'print', archetype: 'archive',
    rationale: 'Early-19th-century commercial papers led with prices current, shipping manifests and commodity quotations; news was a small side column, imagery was nearly absent.',
    publication: 'The Commercial Advertiser', motto: 'Shipping News, Prices Current, and the Intelligence of the Day', price: 'SIX CENTS',
    typography: { head: F.fellSC, body: F.fell, num: F.fell, lead: F.fellSC, fs: '14.5px', lh: '1.36', leadFs: '21px', leadFw: '400', storyFs: '14px', storyFw: '400', sectionFs: '13px', sectionTt: 'uppercase', sectionLs: '.12em', sectionFw: '400', fonts: GF.fell },
    palette: pal({ bg: '#e1d6b8', paper: '#ece2c8', ink: '#1a160d', ink2: '#2d261a', mute: '#6a5e46', rule: '#2c2517', accent: '#1a160d', onAccent: '#ece2c8', up: '#1a160d', down: '#1a160d', link: '#1a160d' }),
    spacing: { maxw: '1180px' }, tokens: { '--row-rule': '1px dotted rgba(44,37,23,.45)', '--cell-pad': '2px 5px' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.MERCANTILE,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'engraved',
    motion: { profile: 'still', enter: 'develop 1s ease-out both' }, loading: 'Setting type…',
    details: ['Prices Current fill two-thirds of the page', 'Shipping and commodity quotations in dense tables'], opts: { founded: 1797 },
  }),
  xp({
    id: 'penny-1830', name: 'Penny Press', from: '1830-01-01', to: '1849-12-31', family: 'print', archetype: 'archive',
    rationale: 'The penny papers of the 1830s–40s: cheap, urban, with bigger headlines, compact columns, and a far wider range of news than the old mercantile sheets.',
    publication: 'The Morning Sun', motto: 'It Shines for All', price: 'ONE CENT',
    typography: { head: F.oldstd, body: F.oldstd, num: F.oldstd, lead: F.oldstd, fs: '14px', lh: '1.34', leadFs: '30px', leadFw: '700', storyFs: '14px', storyFw: '700', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '700', fonts: GF.oldstd },
    palette: pal({ bg: '#e9e1cb', paper: '#f1ead7', ink: '#14110a', ink2: '#2a2417', mute: '#6b6048', rule: '#2a2417', accent: '#14110a', onAccent: '#f1ead7', up: '#14110a', down: '#14110a', link: '#14110a' }),
    spacing: { maxw: '1220px' }, tokens: { '--row-rule': '1px dotted rgba(42,36,23,.4)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.PENNY,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'engraved', headlineCase: 'upper',
    motion: { profile: 'still', enter: 'develop .9s ease-out both' }, loading: 'Setting type…',
    details: ['Banner headline across five compact columns', '“City Items” column of short local news'], opts: { founded: 1833 },
  }),
  xp({
    id: 'victorian-1850', name: 'Illustrated Victorian Press', from: '1850-01-01', to: '1869-12-31', family: 'print', archetype: 'victorian',
    rationale: 'Illustrated weeklies and metropolitan dailies of the mid-Victorian period: ornate mastheads, engraved image frames, fine decorative lines, dense market tables.',
    publication: 'The Illustrated Courier', motto: 'A Journal of Commerce, Politics and the Arts', price: 'TWO PENCE',
    typography: { head: F.fellSC, body: F.fell, num: F.fell, lead: F.fellDP, fs: '14.5px', lh: '1.38', leadFs: '26px', leadFw: '400', storyFs: '14.5px', storyFw: '400', sectionFs: '13px', sectionTt: 'uppercase', sectionLs: '.14em', sectionFw: '400', fonts: [...GF.fell, ...GF.black] },
    palette: pal({ bg: '#e4d8bd', paper: '#efe5cc', ink: '#18130b', ink2: '#2b2418', mute: '#6a5d44', rule: '#2e2616', accent: '#6a2218', onAccent: '#f1e7ce', up: '#18130b', down: '#18130b', link: '#18130b' }),
    background: 'radial-gradient(ellipse at 50% -10%, rgba(255,246,220,.6), transparent 55%), repeating-radial-gradient(circle at 70% 60%, rgba(70,50,25,.03) 0 1px, transparent 1px 3px), #e4d8bd',
    spacing: { maxw: '1180px' }, tokens: { '--row-rule': '1px dotted rgba(46,38,22,.4)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.VICTORIAN,
    interactions: ['section-jump', 'expand-articles'], decor: ['engraved-border', 'fleuron', 'ornament-rule', 'ink-grain'], chart: 'engraved',
    motion: { profile: 'still', enter: 'develop 1s ease-out both' }, loading: 'Setting type…',
    details: ['Engraved frame around the lead article', 'Ornate masthead with side vignettes'], opts: { founded: 1842 },
  }),
  xp({
    id: 'industrial-1870', name: 'Industrial Financial Paper', from: '1870-01-01', to: '1889-12-31', family: 'print', archetype: 'archive',
    rationale: 'Post-Civil-War financial dailies: confident business identity, exchange quotations in structured columns, railway and bank stocks, a ticker-tape strip.',
    publication: 'The Financial Chronicle', motto: 'Devoted to Commerce, Banking and the Railways', price: 'FOUR CENTS',
    typography: { head: F.oldstd, body: F.bask, num: F.oldstd, lead: F.oldstd, fs: '14.5px', lh: '1.4', leadFs: '24px', leadFw: '700', storyFs: '14px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.16em', sectionFw: '700', fonts: [...GF.oldstd, ...GF.bask] },
    palette: pal({ bg: '#e8e0c9', paper: '#f2ecd8', ink: '#13110b', ink2: '#26221a', mute: '#675d46', rule: '#26221a', accent: '#143a2e', onAccent: '#f2ecd8', up: '#143a2e', down: '#7a1a14', link: '#13110b' }),
    spacing: { maxw: '1240px' }, tokens: { '--row-rule': '1px solid rgba(38,34,26,.18)', '--cell-pad': '2px 6px' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.INDUSTRIAL,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'engraved', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .9s ease-out both' }, loading: 'Setting type…',
    details: ['Ticker-tape strip under the masthead', 'Exchange quotations in ruled financial columns'], opts: { founded: 1865 },
  }),
  xp({
    id: 'turn-1890', name: 'Turn-of-the-Century Illustrated Daily', from: '1890-01-01', to: '1899-12-31', family: 'print', archetype: 'broadsheet',
    rationale: 'The 1890s "yellow press" era: large display headlines, decorative advertisements, strong illustration and editorial hierarchy, multi-deck banner heads.',
    publication: 'The Evening World-Herald', motto: 'Circulation Larger Than Any Other Paper in the City', price: 'ONE CENT',
    typography: { head: F.slab, body: F.oldstd, num: F.oldstd, lead: F.slab, fs: '14px', lh: '1.34', leadFs: '22px', leadFw: '400', storyFs: '14px', storyFw: '400', sectionFs: '13px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '400', fonts: [...GF.slab, ...GF.oldstd, ...GF.black] },
    palette: pal({ bg: '#e9dfc2', paper: '#f4ecd3', ink: '#100d07', ink2: '#2a2415', mute: '#6a5d3f', rule: '#1e1a10', accent: '#a3231a', onAccent: '#f6eed6', up: '#100d07', down: '#a3231a', link: '#100d07' }),
    spacing: { maxw: '1260px' }, tokens: { '--row-rule': '1px dotted rgba(30,26,16,.4)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.TURN_OF_CENTURY,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain', 'engraved-border'], chart: 'print', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .9s ease-out both' }, loading: 'Setting type…',
    details: ['Multi-deck banner headline', 'Boxed decorative advertisements'], opts: { founded: 1887 },
  }),

  // ======================================================================= B. 1900–1949
  xp({
    id: 'edwardian-1900', name: 'Edwardian Newspaper', from: '1900-01-01', to: '1909-12-31', family: 'print', archetype: 'broadsheet',
    rationale: 'Edwardian dailies: six or more tightly ruled columns, dense stacked headlines, fine ornamental borders, minimal photography.',
    publication: 'The Daily Standard', motto: 'All the News That Is Fit to Print — and More', price: 'ONE CENT',
    typography: { head: F.oldstd, body: F.oldstd, num: F.oldstd, lead: F.oldstd, fs: '13.5px', lh: '1.34', leadFs: '20px', leadFw: '700', storyFs: '13px', storyFw: '700', sectionFs: '11.5px', sectionTt: 'uppercase', sectionLs: '.16em', sectionFw: '700', fonts: [...GF.oldstd, ...GF.black] },
    palette: pal({ bg: '#e7e1cf', paper: '#f0ebda', ink: '#0f0d08', ink2: '#26221a', mute: '#675f49', rule: '#1c1910', accent: '#0f0d08', onAccent: '#f0ebda', up: '#0f0d08', down: '#0f0d08', link: '#0f0d08' }),
    spacing: { maxw: '1320px' }, tokens: { '--row-rule': '1px dotted rgba(28,25,16,.4)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.EDWARDIAN,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'engraved-border', 'ink-grain'], chart: 'print', ticker: 'none',
    motion: { profile: 'still', enter: 'develop .8s ease-out both' }, loading: 'Setting type…',
    details: ['Six-column ruled grid', 'Fine ornamental rule around the banner'], opts: { founded: 1896 },
  }),
  xp({
    id: 'earlymod-1910', name: 'Early Modern Newspaper', from: '1910-01-01', to: '1913-12-31', family: 'print', archetype: 'broadsheet',
    rationale: 'Early 1910s metropolitan dailies: cleaner four-column grids, bolder serif headlines, illustrated department-store advertisements.',
    publication: 'The Metropolitan Tribune', motto: 'The Newspaper of the Business Day', price: 'ONE CENT',
    typography: { head: F.oldstd, body: F.bask, num: F.oldstd, lead: F.oldstd, fs: '14px', lh: '1.4', leadFs: '23px', leadFw: '700', storyFs: '14px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.14em', sectionFw: '700', fonts: [...GF.oldstd, ...GF.bask] },
    palette: pal({ bg: '#ece6d3', paper: '#f5f1e2', ink: '#0f0d08', ink2: '#26221a', mute: '#6a624b', rule: '#1c1910', accent: '#1c3a5e', onAccent: '#f5f1e2', up: '#0f0d08', down: '#0f0d08', link: '#0f0d08' }),
    spacing: { maxw: '1260px' }, tokens: { '--row-rule': '1px solid rgba(28,25,16,.15)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.EARLY_MODERN,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'print', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .8s ease-out both' }, loading: 'Setting type…',
    details: ['Cleaner four-column grid', 'Boxed illustrated advertisements'], opts: { founded: 1904 },
  }),
  xp({
    id: 'wartime-1914', name: 'Wartime Dispatch Sheet', from: '1914-01-01', to: '1918-12-31', family: 'print', archetype: 'wire',
    rationale: 'Great War bulletins and extras: urgent oversized headlines, numbered dispatches, restrained black-and-red printing. A design language only — no war news is implied for any given date.',
    publication: 'The Daily Bulletin', motto: 'Latest Dispatches by Cable and Wire', price: 'ONE CENT',
    typography: { head: F.slab, body: F.oldstd, num: F.courier, lead: F.slab, fs: '14.5px', lh: '1.4', leadFs: '30px', leadFw: '400', storyFs: '15px', storyFw: '400', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.18em', sectionFw: '400', fonts: [...GF.slab, ...GF.oldstd, ...GF.courier] },
    palette: pal({ bg: '#d8d1bc', paper: '#e6dfca', ink: '#14110b', ink2: '#2b261a', mute: '#6b6350', rule: '#1c1910', accent: '#8b1a1a', onAccent: '#f2ead3', up: '#14110b', down: '#8b1a1a', link: '#14110b' }),
    spacing: { maxw: '1100px' }, tokens: { '--row-rule': '1px dotted rgba(28,25,16,.4)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'bulletins', portfolio: 'ledger', composition: C.WARTIME,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'print',
    motion: { profile: 'still', enter: 'develop .7s ease-out both' }, loading: 'Setting type…',
    details: ['Numbered dispatches with a red stamp', 'Restrained two-colour printing'], opts: { mode: 'sheet', founded: 1902 },
  }),
  xp({
    id: 'postwar-1919', name: 'Postwar Financial Paper', from: '1919-01-01', to: '1924-12-31', family: 'print', archetype: 'broadsheet',
    rationale: 'Early-1920s business dailies: tables first, broader white space, calmer headlines — the page of a nation back at work.',
    publication: 'The Wall Street Ledger', motto: 'A Daily Journal of Finance and Business', price: 'TWO CENTS',
    typography: { head: F.oldstd, body: F.bask, num: F.oldstd, lead: F.oldstd, fs: '14.5px', lh: '1.45', leadFs: '22px', leadFw: '700', storyFs: '14px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.14em', sectionFw: '700', fonts: [...GF.oldstd, ...GF.bask] },
    palette: pal({ bg: '#eae4d2', paper: '#f6f2e4', ink: '#12100a', ink2: '#28241a', mute: '#6a624b', rule: '#2a2519', accent: '#173a2c', onAccent: '#f6f2e4', up: '#173a2c', down: '#7a1c12', link: '#12100a' }),
    spacing: { maxw: '1220px', sectionGap: '22px' }, tokens: { '--row-rule': '1px solid rgba(42,37,25,.12)', '--cell-pad': '3px 6px' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.POSTWAR_FIN,
    interactions: ['section-jump', 'expand-articles'], decor: ['ornament-rule', 'ink-grain'], chart: 'print', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .8s ease-out both' }, loading: 'Setting type…',
    details: ['Market tables lead the page', 'Wider margins and calmer rules'], opts: { founded: 1909 },
  }),
  xp({
    id: 'deco-1925', name: 'Roaring Twenties Financial Daily', from: '1925-01-01', to: '1929-12-31', family: 'print', archetype: 'deco',
    rationale: 'Late-1920s metropolitan dailies and bank-hall graphics: Art Deco chevrons and stepped dividers, bold condensed headlines, a market-ticker band across the masthead.',
    publication: 'The New York Evening Ticker', motto: 'Where the Market Speaks First', price: 'THREE CENTS',
    typography: { head: F.jost, body: F.oldstd, num: F.oldstd, lead: F.slab, fs: '14px', lh: '1.38', leadFs: '26px', leadFw: '400', storyFs: '14px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.2em', sectionFw: '700', fonts: [...GF.deco, ...GF.oldstd, ...GF.slab] },
    palette: pal({ bg: '#e6dec6', paper: '#f2ebd4', ink: '#0e0c07', ink2: '#26221a', mute: '#6a5f43', rule: '#1b1710', accent: '#a0782a', onAccent: '#0e0c07', up: '#0e0c07', down: '#8b1a1a', link: '#0e0c07', panel: '#0e0c07' }),
    background: 'repeating-radial-gradient(circle at 17% 33%, rgba(80,60,30,.03) 0 1px, transparent 1px 3px), #e6dec6',
    spacing: { maxw: '1280px' }, tokens: { '--row-rule': '1px dotted rgba(27,23,16,.4)', '--dock-bg': '#0e0c07', '--dock-border': '3px double #a0782a' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.DECO,
    interactions: ['section-jump', 'expand-articles'], decor: ['deco-chevrons', 'ornament-rule', 'ink-grain'], chart: 'print', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .9s ease-out both' }, loading: 'Setting type…',
    details: ['Art Deco stepped masthead with gold rules', 'Ticker band across the nameplate', 'Small original period-style advertisements'], opts: { founded: 1912 },
  }),
  xp({
    id: 'depression-1930', name: 'Depression-Era Newspaper', from: '1930-01-01', to: '1934-12-31', family: 'print', archetype: 'broadsheet',
    rationale: 'Early-1930s dailies: heavy black headlines, compact market tables, stark editorial design with little ornament.',
    publication: 'The Daily Record', motto: 'The Truth, Whatever the Cost', price: 'TWO CENTS',
    typography: { head: F.slab, body: F.oldstd, num: F.oldstd, lead: F.slab, fs: '13.5px', lh: '1.35', leadFs: '26px', leadFw: '400', storyFs: '13.5px', storyFw: '400', sectionFs: '11.5px', sectionTt: 'uppercase', sectionLs: '.18em', sectionFw: '400', fonts: [...GF.slab, ...GF.oldstd] },
    palette: pal({ bg: '#dcd5c0', paper: '#e9e3cf', ink: '#0b0a06', ink2: '#221f16', mute: '#61594a', rule: '#0b0a06', accent: '#0b0a06', onAccent: '#e9e3cf', up: '#0b0a06', down: '#0b0a06', link: '#0b0a06' }),
    spacing: { maxw: '1240px' }, tokens: { '--row-rule': '1px solid rgba(11,10,6,.2)', '--cell-pad': '2px 5px' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.DEPRESSION,
    interactions: ['section-jump', 'expand-articles'], decor: ['ink-grain'], chart: 'print', ticker: 'tape',
    motion: { profile: 'still', enter: 'develop .7s ease-out both' }, loading: 'Setting type…',
    details: ['Solid black banner headline', 'Compact market tables lead the left column'], opts: { founded: 1921 },
  }),
  xp({
    id: 'radio-1935', name: 'Radio News Bulletin', from: '1935-01-01', to: '1939-12-31', family: 'print', archetype: 'radio',
    rationale: 'The golden age of network radio: newspaper-plus-program-guide graphics, a bakelite set with a tuning dial, bulletin panels per station.',
    publication: 'The Radio-Press Bulletin', motto: 'The News, As It Happens, On Every Dial', price: '3¢',
    typography: { head: F.jost, body: F.oldstd, num: F.courier, lead: F.slab, fs: '15px', lh: '1.42', leadFs: '27px', leadFw: '400', storyFs: '15px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.2em', sectionFw: '700', fonts: [...GF.deco, ...GF.oldstd, ...GF.slab, ...GF.courier] },
    palette: pal({ bg: '#2a1c12', paper: '#efe3c4', ink: '#1a110a', ink2: '#2e2218', mute: '#6b5a40', rule: '#4a3322', accent: '#b4521e', onAccent: '#fff3dc', up: '#1d5b34', down: '#9a2a14', link: '#1a110a', panel: '#3b281a' }),
    background: 'radial-gradient(ellipse at 50% 0%, #4a3220, transparent 70%), repeating-linear-gradient(90deg, rgba(0,0,0,.14) 0 2px, transparent 2px 7px), #2a1c12',
    spacing: { maxw: '1080px' }, tokens: { '--radius': '4px', '--dock-bg': '#3b281a', '--dock-border': '2px solid #b4521e', '--modal-bg': '#efe3c4', '--modal-border': '3px double #4a3322' },
    nav: { model: 'dial' }, search: 'inquiry', market: 'board', news: 'bulletins', portfolio: 'ledger', composition: C.RADIO,
    interactions: ['tune-dial', 'expand-articles'], decor: ['grid-paper', 'vignette'], chart: 'print', ticker: 'bulletin', module: 'print',
    motion: { profile: 'subtle', enter: 'develop .8s ease-out both' }, loading: 'Warming up the set…',
    details: ['Working frequency dial: drag the tuner or press a station', 'Station call-sign plate and “ON THE AIR” lamp'], opts: { stations: 4 },
  }),
  xp({
    id: 'wire-1940', name: 'Wire Service Teletype', from: '1940-01-01', to: '1945-12-31', family: 'print', archetype: 'wire',
    rationale: 'Wire-service copy of the 1940s: typewriter type on paper strips, numbered slugs and datelines, restrained graphics. A design language only — no events are implied for any date.',
    publication: 'UNITED WIRE SERVICE', motto: 'Press Wire · Financial Desk', price: undefined,
    typography: { head: F.typewriter, body: F.typewriter, num: F.courier, lead: F.typewriter, fs: '14.5px', lh: '1.5', leadFs: '22px', leadFw: '400', storyFs: '14.5px', storyFw: '400', sectionFs: '12.5px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '400', fonts: GF.typewriter },
    palette: pal({ bg: '#c9c4b2', paper: '#ebe6d3', ink: '#1a1812', ink2: '#2c2a22', mute: '#6a6656', rule: '#8a8572', accent: '#7a1c14', onAccent: '#ebe6d3', up: '#1a1812', down: '#7a1c14', link: '#1a1812' }),
    background: 'repeating-linear-gradient(0deg, rgba(0,0,0,.03) 0 1px, transparent 1px 3px), #c9c4b2',
    spacing: { maxw: '860px' }, tokens: { '--row-rule': '1px dashed rgba(26,24,18,.3)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'tape', news: 'strips', portfolio: 'ledger', composition: C.WIRE,
    interactions: ['section-jump', 'expand-articles'], decor: ['ink-grain', 'paper-fold'], chart: 'print', ticker: 'none',
    motion: { profile: 'subtle', enter: 'develop .6s ease-out both' }, loading: 'Printing…',
    details: ['Each story is a separate torn paper strip', 'Slug lines and sequence numbers'], opts: { mode: 'strips' },
  }),
  xp({
    id: 'postwar-1946', name: 'Postwar Modernism', from: '1946-01-01', to: '1949-12-31', family: 'print', archetype: 'midcentury',
    rationale: 'Late-1940s modernist editorial design: cleaner grids, early sans-serif display type, an asymmetric front page built around the day’s photograph or front-page scan.',
    publication: 'The Daily Courier', motto: 'Financial Edition', price: '5¢',
    typography: { head: F.jost, body: F.bask, num: F.oldstd, lead: F.oldstd, fs: '15px', lh: '1.45', leadFs: '34px', leadFw: '700', storyFs: '15px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.18em', sectionFw: '700', fonts: [...GF.deco, ...GF.bask, ...GF.oldstd] },
    palette: pal({ bg: '#e9e3d0', paper: '#f6f1e1', ink: '#16130d', ink2: '#2b2619', mute: '#6a6350', rule: '#2b2619', accent: '#a8431f', onAccent: '#f6f1e1', up: '#2c5a3a', down: '#a8431f', link: '#16130d', panel: '#efe8d3' }),
    spacing: { maxw: '1220px' }, tokens: { '--row-rule': '1px solid rgba(43,38,25,.14)' },
    nav: { model: 'sections' }, search: 'inquiry', market: 'table', news: 'columns', portfolio: 'ledger', composition: C.POSTWAR_MOD,
    interactions: ['section-jump', 'expand-articles'], decor: ['ink-grain'], chart: 'print', ticker: 'bulletin',
    motion: { profile: 'still', enter: 'develop .8s ease-out both' }, loading: 'Setting type…',
    details: ['Photograph column built from front-page scans', 'Modernist sans-serif department heads'],
  }),
];
