/**
 * Catalog E: one identity per year, 1995–2026. Years that share a design language differ in
 * composition, navigation and interaction rather than just palette.
 */
import * as C from './compositions';
import { F, GF, pal, xp } from './presets';
import type { VisualExperience } from './types';

export const WEB_CATALOG: VisualExperience[] = [
  xp({
    id: 'netscape-1995', name: 'Netscape-Era Document Web', from: '1995-01-01', to: '1995-12-31', family: 'earlyweb', archetype: 'hypertext',
    rationale: 'The browser itself is part of the page: grey chrome, toolbar buttons, a location field, directory buttons and a throbber, over a white document with blue links.',
    publication: 'The Market Time Home Page', motto: 'Welcome to the Money Page',
    typography: { head: F.times, body: F.times, num: "'Courier New', Courier, monospace", lead: F.times, fs: '16px', lh: '1.25', leadFs: '26px', leadFw: '700', storyFs: '16px', storyFw: '400', sectionFs: '20px', sectionFw: '700' },
    palette: pal({ bg: '#c0c0c0', paper: '#ffffff', ink: '#000000', ink2: '#000000', mute: '#555555', rule: '#808080', accent: '#0000ee', onAccent: '#ffffff', up: '#006400', down: '#cc0000', link: '#0000ee', focus: '#0000ee' }),
    spacing: { maxw: '780px', gutter: '14px', mainPad: '10px', radius: '0' },
    tokens: { '--link-deco': 'underline', '--section-ink': '#000', '--chart-line': '#0000ee', '--chart-grid': '#c0c0c0', '--chart-dash': 'none', '--chart-bg': '#fff', '--dock-bg': '#c0c0c0', '--dock-border': '2px outset #fff', '--modal-bg': '#c0c0c0', '--modal-border': '2px outset #fff', '--titlebar-bg': '#000080', '--titlebar-ink': '#fff', '--story-rule': '0', '--empty-style': 'normal' },
    nav: { model: 'links' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.HYPERTEXT,
    interactions: ['hyperlinks', 'directory-browse'], decor: ['netscape-n', 'status-bar'], chart: 'pixel',
    motion: { profile: 'subtle' }, loading: 'Connect: Host contacted, waiting for reply…',
    details: ['Browser toolbar: Back, Forward, Home, Reload all work', 'Directory buttons: What’s New!, What’s Cool!', 'Animated throbber while a page loads', 'Status bar shows the link under the pointer'], opts: { chrome: 'netscape' },
    status: 'complete',
  }),
  xp({
    id: 'personal-1996', name: 'Personal-Homepage Web', from: '1996-01-01', to: '1996-12-31', family: 'earlyweb', archetype: 'personal',
    rationale: 'Hand-built personal homepages: tiled starfield background, cream content boxes, rainbow rules, a visitor counter and a webring footer. Original decorations only.',
    publication: 'Money Stuff Homepage', motto: 'Welcome to my site!',
    typography: { head: F.comic, body: F.times, num: "'Courier New', Courier, monospace", lead: F.comic, fs: '16px', lh: '1.3', leadFs: '26px', leadFw: '700', storyFs: '16px', storyFw: '400', sectionFs: '17px', sectionFw: '700' },
    palette: pal({ bg: '#000066', paper: '#ffffe6', ink: '#000066', ink2: '#000044', mute: '#4a4a8a', rule: '#cc66cc', accent: '#ff00cc', onAccent: '#ffffff', up: '#008000', down: '#cc0000', link: '#0000ff', focus: '#ff00cc' }),
    background: "radial-gradient(#ffffff 1px, transparent 1.4px) 0 0 / 38px 38px, radial-gradient(#9ad 1px, transparent 1.4px) 19px 19px / 38px 38px, #000066",
    spacing: { maxw: '980px', gutter: '10px', mainPad: '10px', radius: '0' },
    tokens: { '--link-deco': 'underline', '--section-ink': '#fff', '--chart-line': '#cc00cc', '--chart-grid': '#d6d6a0', '--chart-dash': '3 2', '--chart-bg': '#ffffe6', '--dock-bg': '#c0c0c0', '--dock-border': '3px ridge #cc66cc', '--modal-bg': '#ffffe6', '--modal-border': '4px ridge #cc66cc', '--titlebar-bg': 'linear-gradient(90deg,#f0f,#00f)', '--titlebar-ink': '#fff', '--story-rule': '0', '--empty-style': 'normal' },
    nav: { model: 'links' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.PERSONAL,
    interactions: ['hyperlinks', 'directory-browse'], decor: ['counter', 'under-construction', 'webring', 'visitor-badge'], chart: 'pixel',
    motion: { profile: 'subtle' }, loading: 'Loading… please be patient!',
    details: ['Visitor counter (counts real visits this session)', 'Under-construction banner with a tiny animated sign', 'Old-school hyperlink hover colours', 'Webring footer links that work'], opts: {},
    status: 'complete',
  }),
  xp({
    id: 'directory-1997', name: 'Directory Portal', from: '1997-01-01', to: '1997-12-31', family: 'earlyweb', archetype: 'directory',
    rationale: 'Yahoo-style web directories: a compact category index in a table, “What’s New”, search box on top, minimal graphics and a lot of underlined links.',
    publication: 'MarketTime', motto: 'The Internet Guide to Money',
    typography: { head: F.arial, body: F.times, num: "'Courier New', Courier, monospace", lead: F.times, fs: '16px', lh: '1.25', leadFs: '26px', leadFw: '700', storyFs: '16px', storyFw: '400', sectionFs: '13px' },
    palette: pal({ bg: '#ffffff', paper: '#ffffff', ink: '#000000', ink2: '#000000', mute: '#555555', rule: '#808080', accent: '#000080', onAccent: '#ffffff', up: '#008000', down: '#ff0000', link: '#0000ee' }),
    spacing: { maxw: '760px', gutter: '10px', radius: '0' }, tokens: { '--link-deco': 'underline', '--section-ink': '#fff', '--chart-line': '#0000ee', '--chart-grid': '#c0c0c0', '--chart-dash': 'none', '--chart-w': '1', '--chart-bg': '#fff', '--chart-border': '2px inset #c0c0c0' },
    nav: { model: 'links' }, search: 'form', market: 'table', news: 'directory', portfolio: 'form',
    interactions: ['hyperlinks', 'directory-browse'], decor: ['counter'], chart: 'pixel', loading: 'Loading...',
    details: ['Two-column category directory with item counts', '“What’s New!” list with NEW flags', 'Browse by category opens a real search'], opts: { native: true, skin: 'earlyweb' },
    status: 'complete',
  }),
  xp({
    id: 'win98-1998', name: 'Windows 98-Era Finance Site', from: '1998-01-01', to: '1998-12-31', family: 'earlyweb', archetype: 'win98',
    rationale: 'Late-90s corporate finance sites built to look like the desktop around them: grey beveled bars, dense link grids, a quick-links column and a status bar.',
    publication: 'MarketTime Online', motto: 'Investor Center',
    typography: { head: F.tahoma, body: F.tahoma, num: F.tahoma, lead: F.times, fs: '12px', lh: '1.35', leadFs: '20px', leadFw: '700', storyFs: '12px', storyFw: '400', sectionFs: '12px', sectionFw: '700' },
    palette: pal({ bg: '#c0c0c0', paper: '#ffffff', panel: '#d4d0c8', ink: '#000000', ink2: '#000000', mute: '#555555', rule: '#808080', accent: '#000080', onAccent: '#ffffff', up: '#006400', down: '#cc0000', link: '#0000cc', focus: '#000080' }),
    spacing: { maxw: '980px', gutter: '6px', mainPad: '6px', radius: '0', cellPad: '1px 4px' },
    tokens: { '--link-deco': 'underline', '--section-ink': '#fff', '--chart-line': '#000080', '--chart-grid': '#c0c0c0', '--chart-dash': 'none', '--chart-bg': '#fff', '--chart-border': '2px inset #c0c0c0', '--dock-bg': '#c0c0c0', '--dock-border': '2px outset #fff', '--modal-bg': '#c0c0c0', '--modal-border': '2px outset #fff', '--modal-shadow': '2px 2px 0 #000', '--titlebar-bg': 'linear-gradient(90deg,#000080,#1084d0)', '--titlebar-ink': '#fff', '--story-rule': '0', '--story-pad': '2px 0' },
    nav: { model: 'links' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.WIN98,
    interactions: ['hyperlinks', 'directory-browse', 'dropdown-nav'], decor: ['bevel', 'status-bar', 'start-bar'], chart: 'pixel',
    motion: { profile: 'still' }, loading: 'Loading…',
    details: ['Quick-links column that opens real category searches', 'Beveled toolbar buttons and a status bar', 'Taskbar-style footer with a clock'], opts: {},
    status: 'complete',
  }),
  xp({
    id: 'portal-1999', name: 'Dot-Com Portal', from: '1999-01-01', to: '1999-12-31', family: 'portal', archetype: 'portal',
    rationale: 'Late-90s “everything” portals: coloured tab navigation, a scrolling market ticker, banner ad modules, and a search box above a dense three-column page.',
    publication: 'MarketTime', motto: 'Your Window on Wall Street',
    typography: { head: F.verdana, body: F.verdana, num: F.verdana, lead: F.times, fs: '12px', lh: '1.35', leadFs: '22px', leadFw: '700', storyFs: '12px', storyFw: '400', sectionFs: '12px' },
    palette: pal({ bg: '#ffffff', paper: '#ffffff', panel: '#eeeeee', ink: '#000000', ink2: '#222222', mute: '#666666', rule: '#999999', accent: '#003366', onAccent: '#ffffff', up: '#008000', down: '#cc0000', link: '#0000cc' }),
    spacing: { maxw: '800px', gutter: '8px', mainPad: '8px', cellPad: '2px 4px' }, tokens: { '--link-deco': 'underline', '--bar': '#336699', '--section-ink': '#fff', '--chart-line': '#0000cc', '--chart-grid': '#cccccc', '--chart-dash': 'none', '--chart-bg': '#fffff0' },
    nav: { model: 'tabs' }, search: 'form', market: 'table', news: 'cards', portfolio: 'form', ticker: 'marquee',
    interactions: ['tab-nav', 'hyperlinks'], decor: ['ticker-bar'], chart: 'pixel', loading: 'Loading...',
    details: ['Scrolling market ticker that pauses on hover', 'Banner-ad module in the right column', 'Compact directory of categories'], opts: { native: true, skin: 'dotcom' },
    status: 'complete',
  }),
  xp({
    id: 'flash-2000', name: 'Flash-Inspired Multimedia Portal', from: '2000-01-01', to: '2000-12-31', family: 'portal', archetype: 'flash',
    rationale: 'The Flash-intro era: a loading bar and a skippable intro, pixel-font navigation buttons, neon-on-dark panels and “movie” frames around content.',
    publication: 'MARKETTIME', motto: 'enter the new economy',
    typography: { head: F.pixel, body: F.verdana, num: F.verdana, lead: F.pixel, fs: '12.5px', lh: '1.4', leadFs: '18px', leadFw: '400', storyFs: '12.5px', storyFw: '700', sectionFs: '10px', sectionTt: 'uppercase', sectionLs: '.08em', fonts: GF.pixel },
    palette: pal({ bg: '#07070f', paper: '#0e0e1e', panel: '#14142a', ink: '#e8f6ff', ink2: '#c9d8ee', mute: '#8aa0c0', rule: '#2a2a55', accent: '#00e0ff', onAccent: '#001018', up: '#39ff88', down: '#ff4d6d', link: '#7ee8ff', focus: '#ff3df0' }),
    background: 'radial-gradient(900px 500px at 15% -10%, rgba(255,61,240,.16), transparent 60%), radial-gradient(900px 500px at 95% 10%, rgba(0,224,255,.14), transparent 60%), #07070f',
    spacing: { maxw: '1040px', gutter: '14px', mainPad: '12px', radius: '2px' },
    tokens: { '--chart-line': '#00e0ff', '--chart-grid': '#1c1c3c', '--chart-dash': '2 3', '--chart-bg': '#0a0a18', '--dock-bg': '#0e0e1e', '--dock-border': '1px solid #00e0ff', '--modal-bg': '#0e0e1e', '--modal-border': '1px solid #ff3df0', '--titlebar-bg': 'linear-gradient(90deg,#ff3df0,#00e0ff)', '--titlebar-ink': '#07070f', '--story-rule': '1px dashed #2a2a55', '--section-ink': '#00e0ff' },
    nav: { model: 'tabs' }, search: 'form', market: 'tiles', news: 'cards', portfolio: 'cards', composition: C.XP_PORTAL,
    interactions: ['tab-nav', 'hyperlinks'], decor: ['scanlines', 'aurora'], chart: 'pixel',
    motion: { profile: 'rich', enter: 'paint .6s steps(6) both', loop: false }, loading: 'LOADING 37%…',
    details: ['Skippable “intro” with a loading bar (Skip Intro works)', 'Pixel-font navigation buttons that glow on hover', 'Neon frames around content “movies”'], opts: { intro: true },
    status: 'complete',
  }),
  xp({
    id: 'xp-2001', name: 'Windows XP-Era Information Service', from: '2001-01-01', to: '2001-12-31', family: 'portal', archetype: 'xp',
    rationale: 'Luna-era software and web: rounded glossy blue title bars, tan control panels, task-pane navigation and a small system status bar.',
    publication: 'MarketTime XP', motto: 'Information for the way you work',
    typography: { head: F.tahoma, body: F.tahoma, num: F.tahoma, lead: F.trebuchet, fs: '12px', lh: '1.4', leadFs: '22px', leadFw: '700', storyFs: '12.5px', storyFw: '700', sectionFs: '12px', sectionFw: '700' },
    palette: pal({ bg: '#3a6ea5', paper: '#ffffff', panel: '#ece9d8', ink: '#000000', ink2: '#1a1a1a', mute: '#5a5a5a', rule: '#aca899', accent: '#245edb', onAccent: '#ffffff', up: '#1b7a1b', down: '#c01010', link: '#0033cc', focus: '#316ac5' }),
    background: 'linear-gradient(180deg, #4a82c4 0, #3a6ea5 240px, #2d5c8f 100%)',
    spacing: { maxw: '1020px', gutter: '10px', mainPad: '10px', radius: '6px', cellPad: '2px 5px' },
    tokens: { '--chart-line': '#245edb', '--chart-grid': '#d5d2c4', '--chart-dash': 'none', '--chart-bg': '#fff', '--chart-border': '1px solid #aca899', '--dock-bg': '#ece9d8', '--dock-border': '1px solid #716f64', '--dock-radius': '8px', '--modal-bg': '#ece9d8', '--modal-border': '1px solid #0831d9', '--modal-radius': '8px 8px 0 0', '--titlebar-bg': 'linear-gradient(180deg,#3d95ff,#0a5ee6 8%,#0054e3 50%,#0a5ee6 92%,#0540b8)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #e0ddd0' },
    nav: { model: 'tabs' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.XP_PORTAL,
    interactions: ['tab-nav', 'collapsible-widgets', 'hyperlinks'], decor: ['status-bar', 'reflection'], chart: 'gloss',
    motion: { profile: 'subtle' }, loading: 'Loading…',
    details: ['Task-pane style collapsible panels', 'Status bar: “Done” / zone indicator', 'Glossy rounded title bars'], opts: { statusBar: true },
    status: 'complete',
  }),
  xp({
    id: 'enterprise-2002', name: 'Enterprise Finance Portal', from: '2002-01-01', to: '2002-12-31', family: 'portal', archetype: 'enterprise',
    rationale: 'Corporate and institutional portals: blue-grey gradients, a left tree of links, breadcrumbs, nested tables and “tabbed panel” boxes.',
    publication: 'MarketTime Institutional', motto: 'Research · Trading · Portfolio Services',
    typography: { head: F.verdana, body: F.verdana, num: F.verdana, lead: F.verdana, fs: '11.5px', lh: '1.4', leadFs: '18px', leadFw: '700', storyFs: '11.5px', storyFw: '700', sectionFs: '11px', sectionFw: '700', sectionTt: 'uppercase', sectionLs: '.04em' },
    palette: pal({ bg: '#dde3ec', paper: '#ffffff', panel: '#eef1f6', ink: '#1a2233', ink2: '#2c3750', mute: '#5d6a82', rule: '#a9b4c8', accent: '#2b4a7a', onAccent: '#ffffff', up: '#146b2e', down: '#b3261e', link: '#0b4a9c' }),
    background: 'linear-gradient(180deg, #c2cde0 0, #dde3ec 160px, #e9edf4 100%)',
    spacing: { maxw: '1040px', gutter: '10px', mainPad: '10px', radius: '3px', cellPad: '2px 6px' },
    tokens: { '--chart-line': '#2b4a7a', '--chart-grid': '#d8deea', '--chart-dash': 'none', '--chart-bg': '#fff', '--chart-border': '1px solid #a9b4c8', '--dock-bg': '#eef1f6', '--dock-border': '1px solid #a9b4c8', '--dock-radius': '3px', '--modal-bg': '#eef1f6', '--modal-border': '1px solid #2b4a7a', '--titlebar-bg': 'linear-gradient(180deg,#4b6ea3,#2b4a7a)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #e1e6ef' },
    nav: { model: 'sidebar' }, search: 'form', market: 'table', news: 'list', portfolio: 'form', composition: C.ENTERPRISE,
    interactions: ['tab-nav', 'directory-browse', 'hyperlinks'], decor: ['bevel'], chart: 'gloss',
    motion: { profile: 'still' }, loading: 'Loading…',
    details: ['Breadcrumb trail that navigates back', 'Left navigation tree with section links', 'Tabbed panels that switch content in place'], opts: {},
    status: 'complete',
  }),
  xp({
    id: 'clean-2003', name: 'Early CSS-Driven Web', from: '2003-01-01', to: '2003-12-31', family: 'web2', archetype: 'web2',
    rationale: 'Web-standards era: table layouts replaced with CSS columns, more white space, a clean left sidebar, Georgia headings with Verdana body.',
    publication: 'MarketTime', motto: 'news and markets',
    typography: { head: F.georgia, body: F.verdana, num: F.verdana, lead: F.georgia, fs: '13px', lh: '1.55', leadFs: '28px', leadFw: '400', storyFs: '14px', storyFw: '700', sectionFs: '13px', sectionFw: '700' },
    palette: pal({ bg: '#ffffff', paper: '#ffffff', panel: '#f6f6f2', ink: '#222222', ink2: '#444444', mute: '#777777', rule: '#dddddd', accent: '#336699', onAccent: '#ffffff', up: '#2a7d2a', down: '#b02020', link: '#336699' }),
    spacing: { maxw: '960px', gutter: '16px', mainPad: '14px', radius: '0', sectionGap: '22px' },
    tokens: { '--link-deco': 'none', '--chart-line': '#336699', '--chart-grid': '#eeeeee', '--chart-dash': 'none', '--chart-bg': '#fff', '--dock-bg': '#f6f6f2', '--dock-border': '1px solid #ddd', '--dock-radius': '0', '--modal-bg': '#fff', '--modal-border': '1px solid #999', '--modal-radius': '0', '--titlebar-bg': '#336699', '--titlebar-ink': '#fff', '--story-rule': '1px solid #eee' },
    nav: { model: 'sidebar' }, search: 'box', market: 'table', news: 'list', portfolio: 'cards', composition: C.CLEAN_CSS,
    interactions: ['hyperlinks', 'tab-nav'], decor: [], chart: 'flat', loading: 'Loading',
    details: ['Left sidebar navigation with underline-on-hover links', 'Roomier typography than the portals before it'], opts: { variant: 'clean' },
  }),
  xp({
    id: 'rounded-2004', name: 'Early Web 2.0', from: '2004-01-01', to: '2004-12-31', family: 'web2', archetype: 'web2',
    rationale: 'The first rounded-corner, soft-gradient sites: friendly Trebuchet headings, green accents, rounded module headers and glossy-lite buttons.',
    publication: 'MarketTime', motto: 'finance, simplified',
    typography: { head: F.trebuchet, body: F.verdana, num: F.verdana, lead: F.trebuchet, fs: '13px', lh: '1.5', leadFs: '28px', leadFw: '700', storyFs: '13.5px', storyFw: '700', sectionFs: '13px', sectionFw: '700' },
    palette: pal({ bg: '#f2f7ea', paper: '#ffffff', panel: '#e6f0d4', ink: '#2a3320', ink2: '#44503a', mute: '#7a8668', rule: '#cfdcb8', accent: '#6aa525', onAccent: '#ffffff', up: '#3a8a1a', down: '#c8321a', link: '#3c7a10' }),
    spacing: { maxw: '980px', gutter: '14px', mainPad: '14px', radius: '10px' },
    tokens: { '--chart-line': '#6aa525', '--chart-fill-a': '#8cc63f', '--chart-grid': '#e3ecd2', '--chart-dash': 'none', '--chart-w': '2', '--chart-bg': '#fff', '--dock-bg': 'linear-gradient(#fff,#e6f0d4)', '--dock-border': '1px solid #b9cf94', '--dock-radius': '14px', '--modal-bg': '#fff', '--modal-radius': '12px', '--modal-border': '1px solid #b9cf94', '--titlebar-bg': 'linear-gradient(#8cc63f,#5f9a1e)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #e3ecd2' },
    background: 'linear-gradient(180deg,#e6f0d4 0,#f2f7ea 240px)',
    nav: { model: 'tabs' }, search: 'box', market: 'table', news: 'cards', portfolio: 'cards', composition: C.ROUNDED_2004,
    interactions: ['tab-nav', 'hyperlinks'], decor: ['beta-badge'], chart: 'gloss', loading: 'Loading',
    details: ['“beta” badge on the logo', 'Rounded module headers with soft gradients'], opts: { variant: 'rounded' },
  }),
  xp({
    id: 'ajax-2005', name: 'AJAX-Era Dashboard', from: '2005-01-01', to: '2005-12-31', family: 'web2', archetype: 'web2',
    rationale: 'Early “web as application” dashboards: panels you can collapse, expand and reorder without a page load, soft gradients and compact controls.',
    publication: 'MarketTime', motto: 'your personalized market page',
    typography: { head: F.verdana, body: F.verdana, num: F.verdana, lead: F.trebuchet, fs: '12.5px', lh: '1.45', leadFs: '22px', leadFw: '700', storyFs: '12.5px', storyFw: '700', sectionFs: '12px', sectionFw: '700' },
    palette: pal({ bg: '#eaf0f8', paper: '#ffffff', panel: '#f3f6fb', ink: '#1d2736', ink2: '#3a475c', mute: '#76839a', rule: '#cdd8e8', accent: '#3b7bbf', onAccent: '#ffffff', up: '#2a8a3a', down: '#c8322a', link: '#1f5fa8' }),
    spacing: { maxw: '1000px', gutter: '12px', mainPad: '12px', radius: '5px' },
    tokens: { '--chart-line': '#3b7bbf', '--chart-fill-a': '#6aa0d8', '--chart-grid': '#e1e8f3', '--chart-dash': 'none', '--chart-w': '2', '--chart-bg': '#fff', '--dock-bg': 'linear-gradient(#fff,#e1e9f5)', '--dock-border': '1px solid #b8c9de', '--dock-radius': '10px', '--modal-bg': '#fff', '--modal-radius': '8px', '--modal-border': '1px solid #9fb6d3', '--titlebar-bg': 'linear-gradient(#6aa0d8,#3b7bbf)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #e1e8f3' },
    background: 'linear-gradient(180deg,#dbe6f4 0,#eaf0f8 200px)',
    nav: { model: 'tabs' }, search: 'box', market: 'table', news: 'cards', portfolio: 'dashboard', composition: C.AJAX_2005,
    interactions: ['tab-nav', 'collapsible-widgets'], decor: [], chart: 'gloss', loading: 'Loading…',
    details: ['Each panel collapses with its − / + toggle and moves with ◀ ▶ without reloading', 'Panel state remembered while you stay in this year'], opts: { variant: 'ajax', collapsible: true },
  }),
  xp({
    id: 'social-2006', name: 'Social-Web Portal Hybrid', from: '2006-01-01', to: '2006-12-31', family: 'web2', archetype: 'web2',
    rationale: 'Portals borrowing from social networks: a saturated blue header bar, a central “feed” of dated items, modular sidebars of widgets.',
    publication: 'MarketTime', motto: 'what’s happening in the markets',
    typography: { head: F.lucida, body: F.lucida, num: F.lucida, lead: F.lucida, fs: '13px', lh: '1.45', leadFs: '22px', leadFw: '700', storyFs: '13.5px', storyFw: '700', sectionFs: '12px', sectionFw: '700' },
    palette: pal({ bg: '#e9ebee', paper: '#ffffff', panel: '#f3f4f6', ink: '#1c1e21', ink2: '#3b3f45', mute: '#7a808a', rule: '#d3d6db', accent: '#2d5da8', onAccent: '#ffffff', up: '#2a8a3a', down: '#c8322a', link: '#2d5da8' }),
    spacing: { maxw: '980px', gutter: '12px', mainPad: '12px', radius: '3px' },
    tokens: { '--chart-line': '#2d5da8', '--chart-fill-a': '#6e90c8', '--chart-grid': '#e4e6ea', '--chart-dash': 'none', '--chart-w': '2', '--chart-bg': '#fff', '--dock-bg': '#fff', '--dock-border': '1px solid #bdc2cc', '--dock-radius': '6px', '--modal-bg': '#fff', '--modal-radius': '4px', '--modal-border': '1px solid #8a93a6', '--titlebar-bg': '#2d5da8', '--titlebar-ink': '#fff', '--story-rule': '1px solid #eceef1' },
    nav: { model: 'tabs' }, search: 'box', market: 'table', news: 'feed', portfolio: 'cards', composition: C.SOCIAL_2006,
    interactions: ['tab-nav', 'hover-cards'], decor: [], chart: 'flat', loading: 'Loading…',
    details: ['Feed items show how long ago they were published (relative to the simulated day)', 'Widget sidebar with market module'], opts: { variant: 'social' },
  }),
  xp({
    id: 'aqua-2007', name: 'Aqua-Inspired Glossy Finance', from: '2007-01-01', to: '2007-12-31', family: 'web2', archetype: 'web2',
    rationale: 'Mac OS X Aqua language on the web: pinstripe backgrounds, glass pill buttons, a reflected logo, gel-style tabs and Lucida Grande type.',
    publication: 'MarketTime', motto: 'finance for everyone',
    typography: { head: F.lucida, body: F.lucida, num: F.lucida, lead: F.lucida, fs: '13px', lh: '1.45', leadFs: '26px', leadFw: '700', storyFs: '13.5px', storyFw: '700', sectionFs: '13px', sectionFw: '700' },
    palette: pal({ bg: '#dfe5ec', paper: '#ffffff', panel: '#eef2f7', ink: '#1d232b', ink2: '#3a4452', mute: '#7a8594', rule: '#c4cfdc', accent: '#2b78d8', onAccent: '#ffffff', up: '#1f9a3a', down: '#d8302a', link: '#1d5fb8' }),
    background: 'repeating-linear-gradient(90deg, rgba(255,255,255,.55) 0 2px, rgba(205,214,226,.55) 2px 4px), #dfe5ec',
    spacing: { maxw: '1040px', gutter: '14px', mainPad: '14px', radius: '8px' },
    tokens: { '--chart-line': '#2b78d8', '--chart-fill-a': '#6aaaf0', '--chart-grid': '#dce4ee', '--chart-dash': 'none', '--chart-w': '2.2', '--chart-bg': '#fff', '--dock-bg': 'linear-gradient(rgba(255,255,255,.95),rgba(214,226,242,.95))', '--dock-border': '1px solid #a9bbd4', '--dock-radius': '16px', '--modal-bg': '#fff', '--modal-radius': '12px', '--modal-border': '1px solid #8aa3c4', '--titlebar-bg': 'linear-gradient(#8cc0f8,#2b78d8 52%,#1f64bd 53%,#3a88e8)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #e1e8f1' },
    nav: { model: 'tabs' }, search: 'box', market: 'table', news: 'cards', portfolio: 'cards', composition: C.AQUA_2007,
    interactions: ['tab-nav', 'dropdown-nav'], decor: ['reflection', 'noise'], chart: 'gloss', loading: 'Loading…',
    details: ['Glass pill buttons with gel highlights', 'Reflected logo under the masthead', 'Pinstripe background'], opts: { variant: 'aqua' },
  }),
  xp({
    id: 'web2-2008', name: 'Rich Web 2.0 Portal', from: '2008-01-01', to: '2008-12-31', family: 'web2', archetype: 'web2',
    rationale: 'Peak Web 2.0: glossy navigation with nested dropdowns, dense widget sidebars, gradients on everything, rounded modules and the “beta” badge.',
    publication: 'MarketTime', motto: 'beta',
    typography: { head: F.lucida, body: F.lucida, num: F.lucida, lead: F.lucida, fs: '13px', lh: '1.45', leadFs: '26px', leadFw: '700', storyFs: '13.5px', storyFw: '700', sectionFs: '13px', sectionFw: '700' },
    palette: pal({ bg: '#e4eef9', paper: '#ffffff', ink: '#222222', ink2: '#444444', mute: '#777777', rule: '#d3dde8', accent: '#2f73cf', onAccent: '#ffffff', up: '#2a9d2a', down: '#d8302a', link: '#1d5fb8' }),
    spacing: { maxw: '990px', radius: '6px' }, tokens: { '--lime': '#8cc63f' },
    nav: { model: 'tabs' }, search: 'box', market: 'table', news: 'cards', portfolio: 'cards',
    interactions: ['tab-nav', 'dropdown-nav'], decor: ['reflection', 'beta-badge'], chart: 'gloss', loading: 'Loading…',
    details: ['Nested dropdown under Markets', 'Orange call-to-action buttons with gel highlights', 'Glossy header with reflection'], opts: { native: true, skin: 'glossy' },
  }),
  xp({
    id: 'dash-2009', name: 'Smartphone-Era Dashboard', from: '2009-01-01', to: '2009-12-31', family: 'skeuo', archetype: 'mobile',
    rationale: 'The first app-store dashboards: dark glass widgets with chrome edges, glossy gauges and “flip” cards, designed for a small screen and scaled up.',
    publication: 'Market Time', motto: 'dashboard',
    typography: { head: F.helv, body: F.helv, num: F.helv, lead: F.helv, fs: '14px', lh: '1.4', leadFs: '24px', leadFw: '700', storyFs: '14.5px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.06em', sectionFw: '700' },
    palette: pal({ bg: '#0e1116', paper: '#1a1f27', panel: '#222834', ink: '#eef2f7', ink2: '#c9d1dc', mute: '#8c97a8', rule: '#323a48', accent: '#4aa3ff', onAccent: '#06121f', up: '#58d68d', down: '#ff6b60', link: '#8cc6ff', focus: '#8cc6ff' }),
    background: 'radial-gradient(800px 500px at 20% -10%, #27405f, transparent 60%), #0e1116',
    spacing: { maxw: '980px', gutter: '14px', mainPad: '14px', radius: '14px' },
    tokens: { '--chart-line': '#58d68d', '--chart-fill-a': '#58d68d', '--chart-grid': '#2a3240', '--chart-dash': 'none', '--chart-w': '2.2', '--chart-bg': '#141922', '--dock-bg': 'linear-gradient(#2b3340,#171c25)', '--dock-border': '1px solid #3b4556', '--dock-radius': '14px', '--modal-bg': '#1a1f27', '--modal-radius': '16px', '--modal-border': '1px solid #3b4556', '--titlebar-bg': 'linear-gradient(#4b5668,#2a3240 50%,#202733 51%,#2a3240)', '--titlebar-ink': '#eef2f7', '--story-rule': '1px solid #2a3240' },
    nav: { model: 'segmented' }, search: 'box', market: 'sparkcards', news: 'cards', portfolio: 'cards', composition: C.AJAX_2005,
    interactions: ['segmented-controls', 'collapsible-widgets', 'hover-cards'], decor: ['reflection', 'noise'], chart: 'skeuo', loading: 'Loading…',
    details: ['Widgets collapse like dashboard cards', 'Glossy chrome title strips and a segmented tab bar'], opts: { skin: 'skeuo', variant: 'dash', collapsible: true },
  }),
  xp({
    id: 'leather-2010', name: 'Textured Skeuomorphic Interface', from: '2010-01-01', to: '2010-12-31', family: 'skeuo', archetype: 'mobile',
    rationale: 'Peak texture: leather, green felt, paper ledgers and real-looking buttons with highlights and inner shadows, layered like objects on a desk.',
    publication: 'Market Time', motto: 'your desk',
    typography: { head: F.georgia, body: F.helv, num: F.helv, lead: F.georgia, fs: '14.5px', lh: '1.4', leadFs: '26px', leadFw: '700', storyFs: '15px', storyFw: '700', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.08em', sectionFw: '700' },
    palette: pal({ bg: '#4a2f1c', paper: '#f4ecd9', panel: '#e7dcc0', ink: '#2a1f12', ink2: '#463725', mute: '#85755d', rule: '#c7b790', accent: '#9a3a1a', onAccent: '#fff3e4', up: '#2f6b3a', down: '#a8321a', link: '#8a3414' }),
    background: 'radial-gradient(900px 500px at 50% -10%, #6a4630, transparent 65%), repeating-linear-gradient(45deg, rgba(0,0,0,.08) 0 2px, transparent 2px 5px), #4a2f1c',
    spacing: { maxw: '860px', gutter: '14px', mainPad: '14px', radius: '8px' },
    tokens: { '--chart-line': '#2f6b3a', '--chart-fill-a': '#2f6b3a', '--chart-grid': '#d9cba5', '--chart-dash': 'none', '--chart-w': '2.2', '--chart-bg': '#f4ecd9', '--dock-bg': 'linear-gradient(#8b5a3a,#5a3820)', '--dock-border': '1px solid #2a180c', '--dock-ink': '#fff3e4', '--dock-radius': '10px', '--modal-bg': '#f4ecd9', '--modal-radius': '10px', '--modal-border': '1px solid #8a7550', '--titlebar-bg': 'linear-gradient(#8b5a3a,#5a3820)', '--titlebar-ink': '#fff3e4', '--story-rule': '1px dashed #c7b790' },
    nav: { model: 'segmented' }, search: 'box', market: 'sparkcards', news: 'cards', portfolio: 'ledger', composition: C.AJAX_2005,
    interactions: ['segmented-controls', 'collapsible-widgets'], decor: ['leather', 'stitches', 'linen'], chart: 'skeuo', loading: 'Loading…',
    details: ['Leather desk surface with stitched edges', 'Paper-ledger cards with torn-edge headers', 'Embossed buttons with pressed states'], opts: { skin: 'skeuo', variant: 'leather', collapsible: false },
  }),
  xp({
    id: 'ios-2011', name: 'iOS-Inspired Skeuomorphism', from: '2011-01-01', to: '2011-12-31', family: 'skeuo', archetype: 'mobile',
    rationale: 'Handheld-app skeuomorphism at its height: a linen background, stitched leather header, segmented controls, tile “cards” with glossy highlights.',
    publication: 'Market Time', motto: 'markets in your pocket',
    typography: { head: F.helv, body: F.helv, num: F.helv, lead: F.helv, fs: '14.5px', lh: '1.4', leadFs: '26px', leadFw: '700', storyFs: '15px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.06em', sectionFw: '600' },
    palette: pal({ bg: '#d5d9df', paper: '#fbfbfb', ink: '#1f2328', ink2: '#3c4148', mute: '#8a8f96', rule: '#d3d6db', accent: '#2e7bd6', onAccent: '#ffffff', up: '#3ba55c', down: '#d9443f', link: '#2e7bd6' }),
    spacing: { maxw: '760px', radius: '8px' }, tokens: {},
    nav: { model: 'segmented' }, search: 'box', market: 'tiles', news: 'cards', portfolio: 'cards',
    interactions: ['segmented-controls', 'tab-nav'], decor: ['linen', 'stitches'], chart: 'skeuo', loading: 'Loading…',
    details: ['Segmented control switches Today / Portfolio / Search', 'Tile cards with gloss and drop shadows'], opts: { native: true, skin: 'skeuo' },
  }),
  xp({
    id: 'hybrid-2012', name: 'Transitional Responsive Web', from: '2012-01-01', to: '2012-12-31', family: 'skeuo', archetype: 'mobile',
    rationale: 'The pivot year: responsive layouts, subtle gradients replacing heavy textures, buttons that are half skeuomorphic, half flat.',
    publication: 'Market Time', motto: 'responsive',
    typography: { head: F.open, body: F.open, num: F.open, lead: F.open, fs: '14.5px', lh: '1.45', leadFs: '28px', leadFw: '600', storyFs: '15px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.06em', sectionFw: '600', fonts: GF.open },
    palette: pal({ bg: '#e9ecf0', paper: '#ffffff', panel: '#f4f6f9', ink: '#222a33', ink2: '#47525f', mute: '#8590a0', rule: '#d8dde4', accent: '#2b87d8', onAccent: '#ffffff', up: '#34a853', down: '#d9453a', link: '#2b87d8' }),
    spacing: { maxw: '980px', gutter: '16px', mainPad: '16px', radius: '5px' },
    tokens: { '--chart-line': '#2b87d8', '--chart-fill-a': '#2b87d8', '--chart-grid': '#e6eaef', '--chart-dash': 'none', '--chart-w': '2', '--chart-bg': '#fff', '--dock-bg': 'linear-gradient(#fff,#eef1f5)', '--dock-border': '1px solid #cdd3dc', '--dock-radius': '8px', '--modal-bg': '#fff', '--modal-radius': '8px', '--modal-border': '1px solid #cdd3dc', '--titlebar-bg': 'linear-gradient(#3b97e8,#2b87d8)', '--titlebar-ink': '#fff', '--story-rule': '1px solid #eceff3' },
    nav: { model: 'segmented' }, search: 'box', market: 'sparkcards', news: 'cards', portfolio: 'cards', composition: C.FLAT_2015,
    interactions: ['segmented-controls', 'tab-nav'], decor: ['noise'], chart: 'flat', loading: 'Loading…',
    details: ['Layout reflows at three breakpoints', 'Gradients are subtle: the last year of gloss'], opts: { skin: 'skeuo', variant: 'hybrid' },
  }),
  xp({
    id: 'metro-2013', name: 'Metro and Early Flat Design', from: '2013-01-01', to: '2013-12-31', family: 'flat', archetype: 'metro',
    rationale: 'Windows 8 “Metro” language and the first flat sites: flat coloured live tiles, oversized light typography, no gradients or shadows.',
    publication: 'Market Time', motto: 'tiles',
    typography: { head: F.segoe, body: F.segoe, num: F.segoe, lead: F.segoe, fs: '15px', lh: '1.4', leadFs: '44px', leadFw: '300', storyFs: '16px', storyFw: '400', sectionFs: '22px', sectionFw: '300', fonts: GF.open },
    palette: pal({ bg: '#1b1b1f', paper: '#26262c', panel: '#2d2d34', ink: '#ffffff', ink2: '#e0e0e6', mute: '#a0a0ab', rule: '#3a3a42', accent: '#00a8e8', onAccent: '#ffffff', up: '#60d46a', down: '#ff5a4d', link: '#7fd3ff', focus: '#ffffff' }),
    spacing: { maxw: '1260px', gutter: '24px', mainPad: '20px', radius: '0' },
    tokens: { '--chart-line': '#ffffff', '--chart-fill-a': '#ffffff', '--chart-grid': '#3a3a42', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.25', '--chart-bg': 'transparent', '--dock-bg': '#2d2d34', '--dock-border': '0', '--dock-radius': '0', '--modal-bg': '#26262c', '--modal-radius': '0', '--modal-border': '0', '--titlebar-bg': '#00a8e8', '--titlebar-ink': '#fff', '--story-rule': '0' },
    nav: { model: 'tiles' }, search: 'box', market: 'tiles', news: 'tiles', portfolio: 'cards', composition: C.METRO_2013,
    interactions: ['tile-nav', 'hyperlinks'], decor: [], chart: 'flat', headlineCase: 'title',
    motion: { profile: 'subtle', enter: 'tile-in .5s ease-out both' }, loading: 'Loading…',
    details: ['Live tiles flip to show the previous close', 'Oversized light headlines and a lowercase pivot header'], opts: {},
  }),
  xp({
    id: 'material-2014', name: 'Material-Inspired Cards', from: '2014-01-01', to: '2014-12-31', family: 'flat', archetype: 'material',
    rationale: 'Material Design’s first year: a coloured app bar, hamburger drawer, layered paper cards with real elevation, a floating action button and purposeful motion.',
    publication: 'Market Time', motto: '',
    typography: { head: F.roboto, body: F.roboto, num: F.roboto, lead: F.roboto, fs: '14.5px', lh: '1.5', leadFs: '34px', leadFw: '400', storyFs: '16px', storyFw: '500', sectionFs: '14px', sectionFw: '500', fonts: GF.roboto },
    palette: pal({ bg: '#eceff1', paper: '#ffffff', panel: '#f5f7f8', ink: '#212121', ink2: '#424242', mute: '#757575', rule: '#e0e0e0', accent: '#3f51b5', onAccent: '#ffffff', up: '#2e7d32', down: '#c62828', link: '#3f51b5' }),
    spacing: { maxw: '1200px', gutter: '16px', mainPad: '16px', radius: '2px' },
    tokens: { '--chart-line': '#3f51b5', '--chart-fill-a': '#3f51b5', '--chart-grid': '#eceff1', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.5', '--chart-bg': 'transparent', '--dock-bg': '#fff', '--dock-border': '0', '--dock-radius': '2px', '--dock-shadow': '0 8px 24px rgba(0,0,0,.25)', '--modal-bg': '#fff', '--modal-radius': '2px', '--modal-border': '0', '--titlebar-bg': '#3f51b5', '--titlebar-ink': '#fff', '--story-rule': '1px solid #eee', '--card-shadow': '0 1px 3px rgba(0,0,0,.2), 0 1px 2px rgba(0,0,0,.24)' },
    nav: { model: 'drawer' }, search: 'omnibar', market: 'sparkcards', news: 'cards', portfolio: 'cards', composition: C.MATERIAL_2014,
    interactions: ['drawer-nav', 'tab-nav'], decor: [], chart: 'flat',
    motion: { profile: 'subtle', enter: 'rise .4s cubic-bezier(.4,0,.2,1) both' }, loading: 'Loading…',
    details: ['Hamburger drawer navigation with scrim', 'Floating action button opens search', 'Cards lift on hover with a real elevation change'], opts: {},
  }),
  xp({
    id: 'flat-2015', name: 'Clean Flat Financial Dashboard', from: '2015-01-01', to: '2015-12-31', family: 'flat', archetype: 'flat',
    rationale: 'Flat design settled: a left rail, white cards with hairline borders, restrained shadows and a blue accent. Index tiles at the top.',
    publication: 'markettime', motto: '',
    typography: { head: F.roboto, body: F.roboto, num: F.roboto, lead: F.roboto, fs: '14.5px', lh: '1.5', leadFs: '30px', leadFw: '500', storyFs: '16px', storyFw: '500', sectionFs: '15px', sectionFw: '500', fonts: GF.roboto },
    palette: pal({ bg: '#f4f5f7', paper: '#ffffff', ink: '#1f2430', ink2: '#4b5563', mute: '#6b7280', rule: '#e5e7eb', accent: '#1e66f5', onAccent: '#ffffff', up: '#0f9d58', down: '#db4437', link: '#1e66f5' }),
    spacing: { maxw: '1240px', radius: '6px' }, tokens: {},
    nav: { model: 'sidebar' }, search: 'box', market: 'tiles', news: 'cards', portfolio: 'cards',
    interactions: ['hyperlinks', 'tab-nav'], decor: [], chart: 'flat', loading: 'Loading…',
    details: ['Large title with an iOS-style segmented control', 'Grouped lists with hairline separators and index cards with sparklines'], opts: { native: true, skin: 'flat15' },
  }),
  xp({
    id: 'portal-2016', name: 'Responsive Finance Portal', from: '2016-01-01', to: '2016-12-31', family: 'flat', archetype: 'flat',
    rationale: 'Modern responsive portals: a strict 12-column grid, four index tiles up top, a chart-led lead story and clearly separated modules.',
    publication: 'Market Time', motto: '',
    typography: { head: F.lato, body: F.lato, num: F.lato, lead: F.lato, fs: '14.5px', lh: '1.5', leadFs: '30px', leadFw: '700', storyFs: '15.5px', storyFw: '700', sectionFs: '13px', sectionTt: 'uppercase', sectionLs: '.06em', sectionFw: '700', fonts: GF.lato },
    palette: pal({ bg: '#eef1f4', paper: '#ffffff', ink: '#1a2330', ink2: '#44505f', mute: '#6a7686', rule: '#dce1e8', accent: '#0a7d8c', onAccent: '#ffffff', up: '#119c5a', down: '#d6342b', link: '#0a6a78' }),
    spacing: { maxw: '1280px', radius: '4px', gutter: '24px' },
    tokens: { '--chart-line': '#0a7d8c', '--chart-fill-a': '#0a7d8c', '--chart-grid': '#e6eaf0', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.5', '--dock-bg': '#fff', '--dock-border': '0', '--dock-radius': '4px', '--dock-shadow': '0 6px 24px rgba(17,24,39,.2)', '--modal-radius': '6px', '--modal-border': '0', '--story-rule': '1px solid #eaeef3' },
    nav: { model: 'topbar' }, search: 'omnibar', market: 'chart-first', news: 'list', portfolio: 'dashboard', composition: C.PORTAL_2016,
    interactions: ['tab-nav', 'hyperlinks', 'chart-scrub'], decor: [], chart: 'flat', loading: 'Loading…',
    details: ['Chart-led hero with 1M / 6M / 1Y / 5Y / Max ranges', 'Twelve-column responsive grid'], opts: { skin: 'cards', variant: 'portal16' },
  }),
  xp({
    id: 'material-2017', name: 'Mature Material Experience', from: '2017-01-01', to: '2017-12-31', family: 'flat', archetype: 'material',
    rationale: 'Refined Material: a taller app bar with scroll collapse, tonal surfaces, subtle ripple on interaction and a rail of live movers.',
    publication: 'Market Time', motto: '',
    typography: { head: F.roboto, body: F.roboto, num: F.roboto, lead: F.roboto, fs: '14.5px', lh: '1.5', leadFs: '32px', leadFw: '400', storyFs: '16px', storyFw: '500', sectionFs: '14px', sectionFw: '500', fonts: GF.roboto },
    palette: pal({ bg: '#f1f3f4', paper: '#ffffff', panel: '#f8f9fa', ink: '#202124', ink2: '#3c4043', mute: '#5f6368', rule: '#dadce0', accent: '#1a73e8', onAccent: '#ffffff', up: '#188038', down: '#d93025', link: '#1a73e8' }),
    spacing: { maxw: '1280px', gutter: '16px', mainPad: '16px', radius: '8px' },
    tokens: { '--chart-line': '#1a73e8', '--chart-fill-a': '#1a73e8', '--chart-grid': '#e8eaed', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.4', '--dock-bg': '#fff', '--dock-border': '0', '--dock-radius': '8px', '--dock-shadow': '0 8px 28px rgba(60,64,67,.3)', '--modal-radius': '8px', '--modal-border': '0', '--titlebar-bg': '#1a73e8', '--titlebar-ink': '#fff', '--story-rule': '1px solid #eceff1', '--card-shadow': '0 1px 2px rgba(60,64,67,.3), 0 1px 3px 1px rgba(60,64,67,.15)' },
    nav: { model: 'drawer' }, search: 'omnibar', market: 'sparkcards', news: 'cards', portfolio: 'cards', composition: C.MATERIAL_2017,
    interactions: ['drawer-nav', 'tab-nav', 'chart-scrub'], decor: [], chart: 'flat',
    motion: { profile: 'subtle', enter: 'rise .4s cubic-bezier(.4,0,.2,1) both' }, loading: 'Loading…',
    details: ['Search omnibar in the app bar', 'Live movers rail beside the cards', 'Rounder 8px surfaces than 2014’s 2px'], opts: { variant: 'm17' },
  }),
  xp({
    id: 'minimal-2018', name: 'Minimal Fintech', from: '2018-01-01', to: '2018-12-31', family: 'modern', archetype: 'minimal',
    rationale: 'Consumer-fintech minimalism: a single reading column, very large type, almost no chrome, hairline rules and one accent colour.',
    publication: 'Market Time', motto: '',
    typography: { head: F.inter, body: F.inter, num: F.plexmono, lead: F.inter, fs: '15.5px', lh: '1.6', leadFs: '40px', leadFw: '700', storyFs: '17px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '600', fonts: [...GF.inter, ...GF.plex] },
    palette: pal({ bg: '#ffffff', paper: '#ffffff', panel: '#fafafa', ink: '#0b0b0f', ink2: '#3a3a44', mute: '#8a8a96', rule: '#ececf0', accent: '#5b4bff', onAccent: '#ffffff', up: '#0a9a64', down: '#e5484d', link: '#0b0b0f' }),
    spacing: { maxw: '1120px', gutter: '24px', mainPad: '28px', radius: '10px', sectionGap: '28px' },
    tokens: { '--lead-ls': '-.03em', '--chart-line': '#5b4bff', '--chart-fill-a': '#5b4bff', '--chart-grid': '#f1f1f5', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.12', '--dock-bg': '#fff', '--dock-border': '1px solid #ececf0', '--dock-radius': '999px', '--dock-shadow': '0 10px 40px rgba(10,10,20,.12)', '--modal-radius': '16px', '--modal-border': '1px solid #ececf0', '--story-rule': '1px solid #f1f1f5' },
    nav: { model: 'topbar' }, search: 'omnibar', market: 'tiles', news: 'list', portfolio: 'cards', composition: C.MINIMAL_2018,
    interactions: ['hyperlinks', 'chart-scrub', 'command-palette'], decor: [], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'rise .5s ease-out both' }, loading: 'Loading',
    details: ['One 720px reading column with a slim sidebar', 'Large tight-tracked headlines'], opts: {},
  }),
  xp({
    id: 'dataterm-2019', name: 'Dark-Mode Financial Terminal', from: '2019-01-01', to: '2019-12-31', family: 'modern', archetype: 'dataterm',
    rationale: 'Pro-trading dark UIs: dense monospace numbers, tight twelve-column panels, restrained accent colours, tabular layouts with live-style tickers.',
    publication: 'MARKET TIME', motto: '',
    typography: { head: F.plex, body: F.plex, num: F.plexmono, lead: F.plex, fs: '13px', lh: '1.4', leadFs: '22px', leadFw: '600', storyFs: '13.5px', storyFw: '500', sectionFs: '11px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '600', fonts: GF.plex },
    palette: pal({ bg: '#0a0c10', paper: '#10141a', panel: '#141922', ink: '#e6e9ef', ink2: '#b9c0cc', mute: '#7d8696', rule: '#222a36', accent: '#f0b429', onAccent: '#14100a', up: '#31d07f', down: '#ff5d6c', link: '#9ec5ff', focus: '#f0b429' }),
    spacing: { maxw: '1480px', gutter: '14px', mainPad: '12px', radius: '3px', cellPad: '2px 6px' },
    tokens: { '--chart-line': '#f0b429', '--chart-fill-a': '#f0b429', '--chart-grid': '#1b222d', '--chart-dash': 'none', '--chart-w': '1.6', '--chart-area-o': '.15', '--dock-bg': '#10141a', '--dock-border': '1px solid #222a36', '--dock-radius': '4px', '--modal-bg': '#10141a', '--modal-radius': '4px', '--modal-border': '1px solid #2c3646', '--titlebar-bg': '#141922', '--titlebar-ink': '#e6e9ef', '--story-rule': '1px solid #1b222d' },
    nav: { model: 'palette' }, search: 'palette', market: 'heat', news: 'list', portfolio: 'dashboard', composition: C.DATATERM_2019,
    interactions: ['command-palette', 'chart-scrub', 'hover-cards'], decor: [], chart: 'flat', ticker: 'terminal',
    motion: { profile: 'still', enter: 'none' }, loading: 'Loading…',
    details: ['⌘K command palette jumps to any company', 'Dense data tables with monospaced figures', 'Status strip with simulated-date clock'], opts: {},
  }),
  xp({
    id: 'retail-2020', name: 'Retail-Trading Boom Interface', from: '2020-01-01', to: '2020-12-31', family: 'modern', archetype: 'retail',
    rationale: 'Mobile-first trading apps: a giant chart as the hero, a watchlist rail, large green/red P&L numbers, pill-shaped actions and a dark surface.',
    publication: 'Market Time', motto: '',
    typography: { head: F.manrope, body: F.manrope, num: F.manrope, lead: F.manrope, fs: '15px', lh: '1.5', leadFs: '32px', leadFw: '800', storyFs: '15.5px', storyFw: '700', sectionFs: '13px', sectionFw: '700', fonts: GF.manrope },
    palette: pal({ bg: '#000000', paper: '#0e0f12', panel: '#16181d', ink: '#ffffff', ink2: '#d3d6dc', mute: '#8a909c', rule: '#23262d', accent: '#00c805', onAccent: '#001a01', up: '#00c805', down: '#ff5000', link: '#ffffff', focus: '#00c805' }),
    spacing: { maxw: '1180px', gutter: '20px', mainPad: '18px', radius: '14px' },
    tokens: { '--chart-line': '#00c805', '--chart-fill-a': '#00c805', '--chart-grid': '#1a1c21', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.12', '--dock-bg': '#16181d', '--dock-border': '1px solid #23262d', '--dock-radius': '999px', '--dock-shadow': '0 16px 48px rgba(0,0,0,.6)', '--modal-bg': '#0e0f12', '--modal-radius': '20px', '--modal-border': '1px solid #23262d', '--story-rule': '1px solid #1a1c21' },
    nav: { model: 'topbar' }, search: 'omnibar', market: 'chart-first', news: 'list', portfolio: 'dashboard', composition: C.RETAIL_2020,
    interactions: ['chart-scrub', 'hover-cards', 'tab-nav', 'command-palette'], decor: [], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'rise .5s ease-out both' }, loading: 'Loading',
    details: ['Hero chart with 1D / 1M / 1Y scrub', 'Watchlist rail with coloured sparklines', 'Pill-shaped primary actions'], opts: {},
  }),
  xp({
    id: 'glass-2021', name: 'Glassmorphism Fintech', from: '2021-01-01', to: '2021-12-31', family: 'modern', archetype: 'glass',
    rationale: 'Glassmorphism: translucent frosted panels over a soft colour-blob gradient, thin white borders, pastel accents and rounded 20px cards.',
    publication: 'Market Time', motto: '',
    typography: { head: F.manrope, body: F.manrope, num: F.manrope, lead: F.manrope, fs: '14.5px', lh: '1.5', leadFs: '32px', leadFw: '700', storyFs: '15px', storyFw: '600', sectionFs: '13px', sectionFw: '600', fonts: GF.manrope },
    palette: pal({ bg: '#1b1640', paper: 'rgba(255,255,255,.10)', panel: 'rgba(255,255,255,.08)', ink: '#f6f4ff', ink2: '#d8d3f5', mute: '#a8a1d0', rule: 'rgba(255,255,255,.18)', accent: '#ff9be0', onAccent: '#2a0f26', up: '#7dffc0', down: '#ff8fa3', link: '#ffffff', focus: '#ff9be0' }),
    background: 'radial-gradient(600px 400px at 12% 8%, #ff6ad5 0, transparent 60%), radial-gradient(700px 500px at 88% 12%, #4ea3ff 0, transparent 60%), radial-gradient(700px 500px at 50% 100%, #8b5cf6 0, transparent 60%), #1b1640',
    spacing: { maxw: '1200px', gutter: '24px', mainPad: '20px', radius: '20px' },
    tokens: { '--chart-line': '#ffd1f2', '--chart-fill-a': '#ff9be0', '--chart-grid': 'rgba(255,255,255,.12)', '--chart-dash': 'none', '--chart-w': '2.2', '--chart-area-o': '.3', '--chart-bg': 'transparent', '--dock-bg': 'rgba(255,255,255,.14)', '--dock-border': '1px solid rgba(255,255,255,.3)', '--dock-radius': '999px', '--dock-shadow': '0 16px 48px rgba(10,5,40,.5)', '--modal-bg': 'rgba(34,26,82,.82)', '--modal-radius': '24px', '--modal-border': '1px solid rgba(255,255,255,.3)', '--story-rule': '1px solid rgba(255,255,255,.12)', 'color-scheme': 'dark', '--glass-blur': '18px' },
    nav: { model: 'dock' }, search: 'omnibar', market: 'sparkcards', news: 'cards', portfolio: 'cards', composition: C.GLASS_2021,
    interactions: ['dock-nav', 'hover-cards', 'chart-scrub', 'command-palette'], decor: ['aurora', 'noise'], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'focus-in .6s ease-out both' }, loading: 'Loading',
    details: ['Frosted-glass panels with a real backdrop blur over a drifting colour mesh', 'Floating frosted navigation pill with a sliding highlight'], opts: {},
  }),
  xp({
    id: 'bento-2022', name: 'Bento Data Dashboard', from: '2022-01-01', to: '2022-12-31', family: 'modern', archetype: 'bento',
    rationale: 'Bento-grid dashboards: modular blocks of different sizes, big rounded corners, soft pastel fills, bold numerals and generous gaps.',
    publication: 'Market Time', motto: '',
    typography: { head: F.space, body: F.inter, num: F.space, lead: F.space, fs: '14.5px', lh: '1.5', leadFs: '28px', leadFw: '700', storyFs: '15px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.08em', sectionFw: '700', fonts: GF.space },
    palette: pal({ bg: '#f3efe8', paper: '#ffffff', panel: '#fbf8f2', ink: '#16130e', ink2: '#3c372d', mute: '#7a7366', rule: '#e6e0d4', accent: '#ff5b2e', onAccent: '#ffffff', up: '#13a05a', down: '#e5484d', link: '#16130e' }),
    spacing: { maxw: '1240px', gutter: '24px', mainPad: '24px', radius: '24px', sectionGap: '14px' },
    tokens: { '--chart-line': '#ff5b2e', '--chart-fill-a': '#ff5b2e', '--chart-grid': '#efe9dc', '--chart-dash': 'none', '--chart-w': '2.4', '--chart-area-o': '.14', '--dock-bg': '#16130e', '--dock-ink': '#fff', '--dock-border': '0', '--dock-radius': '999px', '--dock-shadow': '0 12px 40px rgba(22,19,14,.25)', '--modal-radius': '28px', '--modal-border': '0', '--story-rule': '1px solid #efe9dc' },
    nav: { model: 'topbar' }, search: 'omnibar', market: 'tiles', news: 'cards', portfolio: 'dashboard', composition: C.BENTO_2022,
    interactions: ['hover-cards', 'chart-scrub', 'tab-nav', 'command-palette'], decor: [], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'rise .5s ease-out both' }, loading: 'Loading',
    details: ['Index values appear as individual bento tiles', 'Blocks reflow without reordering content'], opts: {},
  }),
  xp({
    id: 'research-2023', name: 'AI-Era Research Interface', from: '2023-01-01', to: '2023-12-31', family: 'modern', archetype: 'research',
    rationale: 'Research assistants and notebooks: a prominent “ask” bar, command palette, citations shown in a contextual side panel, calm neutral surfaces.',
    publication: 'Market Time Research', motto: '',
    typography: { head: F.inter, body: F.inter, num: F.plexmono, lead: F.inter, fs: '15px', lh: '1.6', leadFs: '28px', leadFw: '600', storyFs: '15.5px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.08em', sectionFw: '600', fonts: [...GF.inter, ...GF.plex] },
    palette: pal({ bg: '#f7f7f5', paper: '#ffffff', panel: '#f1f1ee', ink: '#18181b', ink2: '#3f3f46', mute: '#71717a', rule: '#e4e4e0', accent: '#10a37f', onAccent: '#ffffff', up: '#0f9d58', down: '#d93a3a', link: '#0b6e57' }),
    spacing: { maxw: '1280px', gutter: '24px', mainPad: '24px', radius: '12px' },
    tokens: { '--chart-line': '#10a37f', '--chart-fill-a': '#10a37f', '--chart-grid': '#eeeeea', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.12', '--dock-bg': '#fff', '--dock-border': '1px solid #e4e4e0', '--dock-radius': '999px', '--dock-shadow': '0 10px 36px rgba(0,0,0,.12)', '--modal-radius': '16px', '--modal-border': '1px solid #e4e4e0', '--story-rule': '1px solid #eeeeea' },
    nav: { model: 'palette' }, search: 'ask', market: 'sparkcards', news: 'feed', portfolio: 'cards', composition: C.RESEARCH_2023,
    interactions: ['command-palette', 'hover-cards'], decor: [], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'rise .4s ease-out both' }, loading: 'Thinking…',
    details: ['“Ask” bar searches the information available that day', 'Suggested prompts run real searches; a docked panel shows the sources and context behind the summary', '⌘K command palette'], opts: {},
  }),
  xp({
    id: 'spatial-2024', name: 'Premium Spatial Fintech', from: '2024-01-01', to: '2024-12-31', family: 'modern', archetype: 'spatial',
    rationale: 'Spatial interfaces: layered translucent planes with depth, parallax tilt on pointer, soft ambient light, and interactive data layers.',
    publication: 'Market Time', motto: '',
    typography: { head: F.display, body: F.manrope, num: F.display, lead: F.display, fs: '14.5px', lh: '1.5', leadFs: '34px', leadFw: '600', storyFs: '15px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.12em', sectionFw: '600', fonts: GF.sora },
    palette: pal({ bg: '#0a0e17', paper: 'rgba(24,32,50,.72)', panel: 'rgba(30,40,62,.6)', ink: '#eef3ff', ink2: '#c4cee8', mute: '#8493b5', rule: 'rgba(160,185,255,.16)', accent: '#7aa8ff', onAccent: '#071029', up: '#5ee6a8', down: '#ff7a8a', link: '#bcd2ff', focus: '#7aa8ff' }),
    background: 'radial-gradient(900px 600px at 20% -10%, rgba(80,120,255,.25), transparent 60%), radial-gradient(900px 600px at 90% 10%, rgba(120,80,255,.18), transparent 60%), #0a0e17',
    spacing: { maxw: '1260px', gutter: '26px', mainPad: '24px', radius: '22px' },
    tokens: { '--chart-line': '#7aa8ff', '--chart-fill-a': '#7aa8ff', '--chart-grid': 'rgba(160,185,255,.1)', '--chart-dash': 'none', '--chart-w': '2.2', '--chart-area-o': '.25', '--chart-bg': 'transparent', '--dock-bg': 'rgba(24,32,50,.8)', '--dock-border': '1px solid rgba(160,185,255,.25)', '--dock-radius': '999px', '--dock-shadow': '0 24px 60px rgba(0,0,0,.6)', '--modal-bg': 'rgba(20,28,46,.92)', '--modal-radius': '26px', '--modal-border': '1px solid rgba(160,185,255,.25)', '--story-rule': '1px solid rgba(160,185,255,.12)' },
    nav: { model: 'dock' }, search: 'omnibar', market: 'sparkcards', news: 'cards', portfolio: 'dashboard', composition: C.SPATIAL_2024,
    interactions: ['dock-nav', 'hover-cards', 'chart-scrub', 'command-palette'], decor: ['depth', 'aurora'], chart: 'smooth',
    motion: { profile: 'rich', enter: 'focus-in .7s ease-out both' }, loading: 'Loading',
    details: ['Cards tilt toward the pointer with layered depth (disabled for reduced motion)', 'Ambient light follows the active section'], opts: {},
  }),
  xp({
    id: 'finos-2025', name: 'Experimental Financial OS', from: '2025-01-01', to: '2025-12-31', family: 'experimental', archetype: 'finos',
    rationale: 'A financial “operating system”: floating app panels with a menu bar and dock, adaptive layouts that rearrange by pane width, and polished transitions.',
    publication: 'Market OS', motto: '',
    typography: { head: F.inter, body: F.inter, num: F.plexmono, lead: F.inter, fs: '14px', lh: '1.5', leadFs: '26px', leadFw: '600', storyFs: '14.5px', storyFw: '600', sectionFs: '12px', sectionFw: '600', fonts: [...GF.inter, ...GF.plex] },
    palette: pal({ bg: '#12141a', paper: '#1b1e26', panel: '#222631', ink: '#f1f3f8', ink2: '#c6cbd8', mute: '#8890a3', rule: '#2c3140', accent: '#7dd3a8', onAccent: '#08140e', up: '#6ee7a0', down: '#ff7a85', link: '#a8d8ff', focus: '#7dd3a8' }),
    background: 'radial-gradient(900px 600px at 80% 0%, rgba(125,211,168,.12), transparent 60%), linear-gradient(180deg,#171a22,#0e1016)',
    spacing: { maxw: '1480px', gutter: '16px', mainPad: '14px', radius: '14px' },
    tokens: { '--chart-line': '#7dd3a8', '--chart-fill-a': '#7dd3a8', '--chart-grid': '#262a37', '--chart-dash': 'none', '--chart-w': '2', '--chart-area-o': '.18', '--dock-bg': 'rgba(34,38,49,.82)', '--dock-border': '1px solid #343a4c', '--dock-radius': '20px', '--dock-shadow': '0 20px 50px rgba(0,0,0,.55)', '--modal-bg': '#1b1e26', '--modal-radius': '18px', '--modal-border': '1px solid #343a4c', '--titlebar-bg': '#222631', '--titlebar-ink': '#f1f3f8', '--story-rule': '1px solid #262a37' },
    nav: { model: 'dock' }, search: 'palette', market: 'heat', news: 'feed', portfolio: 'dashboard', composition: C.FINOS_2025,
    interactions: ['dock-nav', 'movable-windows', 'command-palette'], decor: ['depth'], chart: 'smooth',
    motion: { profile: 'subtle', enter: 'focus-in .6s ease-out both' }, loading: 'Loading',
    details: ['Panels are windows: focus, raise and collapse them', 'Menu bar with clock and ⌘K palette', 'Dock launches Home / Portfolio / Search'], opts: {},
  }),
  xp({
    id: 'liquid-2026', name: 'Liquid-Glass Contemporary', from: '2026-01-01', to: '2999-12-31', family: 'experimental', archetype: 'liquid',
    rationale: 'Contemporary premium interface: refractive liquid-glass controls with specular edges, fluid morphing of the active pill, and refined motion.',
    publication: 'Market Time', motto: '',
    typography: { head: F.display, body: F.manrope, num: F.display, lead: F.display, fs: '14.5px', lh: '1.5', leadFs: '36px', leadFw: '600', storyFs: '15px', storyFw: '600', sectionFs: '12px', sectionTt: 'uppercase', sectionLs: '.1em', sectionFw: '600', fonts: GF.sora },
    palette: pal({ bg: '#e8eef7', paper: 'rgba(255,255,255,.55)', panel: 'rgba(255,255,255,.4)', ink: '#101828', ink2: '#344054', mute: '#667085', rule: 'rgba(255,255,255,.7)', accent: '#2f6df6', onAccent: '#ffffff', up: '#0f9d58', down: '#e5484d', link: '#1f4fd1', focus: '#2f6df6' }),
    background: 'radial-gradient(700px 500px at 10% 0%, #ffd8ec, transparent 60%), radial-gradient(800px 600px at 95% 10%, #cfe3ff, transparent 60%), radial-gradient(700px 500px at 50% 100%, #e3dcff, transparent 60%), #e8eef7',
    spacing: { maxw: '1240px', gutter: '26px', mainPad: '24px', radius: '26px' },
    tokens: { '--chart-line': '#2f6df6', '--chart-fill-a': '#2f6df6', '--chart-grid': 'rgba(16,24,40,.08)', '--chart-dash': 'none', '--chart-w': '2.4', '--chart-area-o': '.18', '--chart-bg': 'transparent', '--dock-bg': 'rgba(255,255,255,.55)', '--dock-border': '1px solid rgba(255,255,255,.85)', '--dock-radius': '999px', '--dock-shadow': '0 20px 50px rgba(30,50,120,.2), inset 0 1px 0 rgba(255,255,255,.9)', '--modal-bg': 'rgba(255,255,255,.8)', '--modal-radius': '30px', '--modal-border': '1px solid rgba(255,255,255,.9)', '--story-rule': '1px solid rgba(16,24,40,.08)' },
    nav: { model: 'dock' }, search: 'omnibar', market: 'sparkcards', news: 'cards', portfolio: 'dashboard', composition: C.LIQUID_2026,
    interactions: ['dock-nav', 'hover-cards', 'chart-scrub', 'command-palette'], decor: ['aurora', 'depth'], chart: 'smooth',
    motion: { profile: 'rich', enter: 'focus-in .7s ease-out both' }, loading: 'Loading',
    details: ['Navigation pill morphs between destinations', 'Specular glass edges and refraction on controls'], opts: {},
  }),
];
